Updated test scripts to use nmg_xtest

diff --git a/test/ddns-test b/test/ddns-test
--- a/test/ddns-test
+++ b/test/ddns-test
@@ -5,76 +5,12 @@
 #
 # shellcheck disable=SC2034,SC1090,SC2123
 
-# load common.conf
-TEST_COMMON=${TEST_COMMON:-conf/common.conf}
-{ [[ -r ${TEST_COMMON} ]] && . "${TEST_COMMON}"; } ||
-  { echo >&2 "Unable to load ${TEST_COMMON}"; exit 2; }
-
-{ [[ ${XTEST_SETUP} ]] && . "${XTEST_SETUP}"; } ||
-  { echo >&2 "Unable to load xtest_setup"; exit 2; }
-
-[[ $EUID == 0 ]] && xtest::fail "Never run as root!"
-
-NMDDNS=${NMDDNS:-${NMUTILS}/ddns-functions}
-
-# ensure includes pass parse test
-shtest::parse "${NMDDNS}" || shtest::fatal
-
-# verify required
-NMG_REQUIRED="99.0.0"
-
-(. "${NMDDNS}" 2>/dev/null &&
-   xtest::fail "FATAL: ${NMDDNS} loaded when NMG_REQUIRED=${NMG_REQUIRED}" || :) || exit 1
-
-unset NMG_REQUIRED
-NMDDNS_REQUIRED="99.0.0"
-(. "${NMDDNS}" 2>/dev/null &&
-   xtest::fail "FATAL: ${NMDDNS} loaded when NMDDNS_REQUIRED=${NMDDNS_REQUIRED}" || :) || exit 1
+NMG_XTEST=${NMG_XTEST:-conf/nmg_xtest}
+{ [[ -r ${NMG_XTEST} ]] && . "${NMG_XTEST}"; } ||
+  { echo >&2 "Unable to load ${NMG_XTEST}"; exit 2; }
 
 # min-version for tests
 NMDDNS_REQUIRED="1.4.4"
-
-# less noise
-export NMG_TAG=''
-
-. "${NMDDNS}" || exit 1
-
-# don't let general-functions use external commands
-# (except those defined in config)
-PATH=''
-
-# these tests require MOCK_ECHO=1 to check command actions
-export MOCK_ECHO=1
-
-# need rundir
-[[ $RUNDIR && -d $RUNDIR ]] || xtest::fail "\$RUNDIR doesn't exist!"
-# need output directory
-[[ $TEST_OUT && -d $TEST_OUT ]] || xtest::fail "\$TEST_OUT is unset/missing!"
-XLOG="$TEST_OUT/ddns.log" XERR="$TEST_OUT/ddns.err"
-
-xwrap() {
-  local cmd=${1-}
-  [[ ${cmd} ]] || xtest::fail "xwrap: missing <cmd>"
-  shift
-  "${cmd}" &>"${XERR}" 4>"${XLOG}" "$@"
-}
-
-xrm() {
-  [[ ${1-} ]] || return 0
-  command -p rm -f "$@"
-}
-
-xwrap_cleanup() {
-  local rc=$?
-  [[ -e ${XERR} ]] && { cat "${XERR}"; xrm "${XERR}"; }
-  [[ -e ${XLOG} ]] && { cat "${XLOG}"; xrm "${XLOG}"; }
-  exit ${rc}
-}
-
-read_value() { # <var> (<stdin)
-  local IFS; unset IFS
-  read -r -d '' "$1" || :
-}
 
 xtest::group4::ddns() {
   local out xpat xstate cnf
@@ -90,7 +26,7 @@ xtest::group4::ddns() {
   DDNS_ZONE=example.test DDNS_RREC_A_NAME=www.example.test
   xwrap nmddns_update A
   xtest D1 t "(<remove A>) returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Removing www.example.test A
 	${NMDDNS_NSUPDATE} => nsupdate -t 3
 	server 127.0.0.1
@@ -103,7 +39,7 @@ xtest::group4::ddns() {
   export DIG_MOCK_FAIL=5
   xwrap nmddns_update A
   xtest D2 25 "(<dig fail 5>) returns 25"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	ERR: FAIL(5) ${NMDDNS_DIG} @127.0.0.1 +short +retry=2 +time=3 +time=1 +retry=2 A www.example.test
 	ERR: Removal of www.example.test A failed
 	EOF
@@ -113,7 +49,7 @@ xtest::group4::ddns() {
   export NSUPDATE_MOCK_FAIL=5
   xwrap nmddns_update A
   xtest D3 5 "(<nsupdate fail 5>) returns 5"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Removing www.example.test A
 	ERR: FAIL(5) ${NMDDNS_NSUPDATE} -t 3
 	ERR: DNS update to server 127.0.0.1 failed for www.example.test A
@@ -123,7 +59,7 @@ xtest::group4::ddns() {
 
   xwrap nmddns_update A 192.168.55.1
   xtest D4 t "(A <private>) returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Removing www.example.test A
 	${NMDDNS_NSUPDATE} => nsupdate -t 3
 	server 127.0.0.1
@@ -136,7 +72,7 @@ xtest::group4::ddns() {
   DDNS_RREC_A_FALLBACK=203.0.113.8
   xwrap nmddns_update A 192.168.55.1/24
   xtest D5 t "(A <private>) FALLBACK returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Setting www.example.test A to 203.0.113.8
 	${NMDDNS_NSUPDATE} => nsupdate -t 3
 	server 127.0.0.1
@@ -154,7 +90,7 @@ xtest::group4::ddns() {
   xrm "$xstate"
   xwrap nmddns_update A 192.168.55.1/24 "$xpat"
   xtest D6 t "(A <private>) PRIVATE=1 returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Setting www.example.test A to 192.168.55.1
 	${NMDDNS_NSUPDATE} => nsupdate -t 3
 	server 127.0.0.1
@@ -171,7 +107,7 @@ xtest::group4::ddns() {
   xrm "$xstate"
   xwrap nmddns_update A "" "$xstate"
   xtest D7 t "(<bad state-pat>) returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	ERR: nmddns_update: <state-pat> must include string '@RREC@'
 	Removing www.example.test A
 	${NMDDNS_NSUPDATE} => nsupdate -t 3
@@ -203,7 +139,7 @@ xtest::group4::ddns() {
   DDNS_RREC_A_VALUE="*"
   xwrap nmddns_update A 203.0.113.10
   xtest D11 t "(A) _VALUE=*, returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Removing www.example.test A
 	${NMDDNS_NSUPDATE} => nsupdate -t 3
 	server 127.0.0.1
@@ -216,7 +152,7 @@ xtest::group4::ddns() {
   unset DDNS_RREC_A_VALUE
   xwrap nmddns_update A 203.0.113.10
   xtest D12 t "(A <pub>) returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Setting www.example.test A to 203.0.113.10
 	${NMDDNS_NSUPDATE} => nsupdate -t 3
 	server 127.0.0.1
@@ -229,7 +165,7 @@ xtest::group4::ddns() {
 
   xwrap nmddns_update A "203.0.113.10,203.0.113.20"
   xtest D13 t "(A <2 pub>) returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Setting www.example.test A to 203.0.113.10,203.0.113.20
 	${NMDDNS_NSUPDATE} => nsupdate -t 3
 	server 127.0.0.1
@@ -249,7 +185,7 @@ xtest::group4::ddns() {
   DDNS_RREC_TXT_LISTSEP=:
   xwrap nmddns_update TXT "\"some value\":\"another value\""
   xtest D15 t "(TXT <2 new vals>) returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Setting mail.example.test TXT to "some value":"another value"
 	${NMDDNS_NSUPDATE} => nsupdate -t 3
 	server 127.0.0.1
@@ -277,7 +213,7 @@ xtest::group4::ddns() {
   DDNS_TTL=300
   xwrap nmddns_update_all up 203.0.113.8 2001:db8:1000:2000::1/64
   xtest D21 t "(<up multi>) returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Setting ipv6.example.test AAAA to 2001:db8:1000:2000::1
 	${NMDDNS_NSUPDATE} => nsupdate -t 3
 	server 127.0.0.1
@@ -305,7 +241,7 @@ xtest::group4::ddns() {
   DDNS_NSUPDATE_TIMEOUT=5
   xwrap nmddns_update_all down
   xtest D22 t "(<down multi>) returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Removing ipv6.example.test AAAA
 	${NMDDNS_NSUPDATE} => nsupdate -t 5
 	server 127.0.0.1
@@ -352,7 +288,7 @@ xtest::group4::ddns() {
   [[ -f $xstate ]]
   xtest D33s f " - removes state file"
   xrm "$xstate"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Removing www.example.test A
 	${NMDDNS_NSUPDATE} => nsupdate -t 2
 	server 127.0.0.1
@@ -380,7 +316,7 @@ xtest::group4::ddns() {
 
   xwrap nmddns_spawn_update_all up "$cnf"
   xtest D41 t "(up) returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
   	Removing www.example.test A
 	${NMDDNS_NSUPDATE} => nsupdate -t 2
 	server 127.0.0.1
@@ -420,7 +356,7 @@ xtest::group5::helper() {
   echo "2001:db8:871a:28c1::2/64" > "$state0"
   xwrap "${NMDDNS_HELPER}"
   xtest H3 t "(<no args>) diff non-active ip, returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Removing www.example.test AAAA
 	${NMDDNS_NSUPDATE} => nsupdate -t 3
 	server 127.0.0.1
@@ -433,7 +369,7 @@ xtest::group5::helper() {
   echo "2001:db8:871a:28c1::1/64" > "$state0"
   xwrap "${NMDDNS_HELPER}"
   xtest H4 t "(<no args>) diff active ip, returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Setting www.example.test AAAA to 2001:db8:871a:28c1::1
 	${NMDDNS_NSUPDATE} => nsupdate -t 3
 	server 127.0.0.1
@@ -447,7 +383,7 @@ xtest::group5::helper() {
   xrm "$state0" "$state1"
   xwrap "${NMDDNS_HELPER}"
   xtest H5 t "(<no args>) missing 2 states, returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Removing www.example.test AAAA
 	${NMDDNS_NSUPDATE} => nsupdate -t 3
 	server 127.0.0.1
@@ -466,33 +402,38 @@ xtest::group5::helper() {
   xrm "$state0" "$state1" "$state2"
 }
 
-main() { # <args>
-  local XNOFILE="$TEST_OUT/no-file" XFILE="$TEST_OUT/ddns file" IFS=-
+test_version() {
+  local NMG_REQUIRED="99.0.0" nmg_log_stderr=1
 
-  # reset (in subshell)
-  shtest::reset
+  shtest::title "Check version requirements"
 
-  # fd 4 used for logger
-  export nmg_log_stderr=4
-  exec 4>&2
+  (. "${NMDDNS}" 2>/dev/null) &&
+    xtest::fail "  FATAL: ${NMDDNS} loaded when NMG_REQUIRED=${NMG_REQUIRED}"
 
-  shtest::reg_file "$XLOG"
-  shtest::reg_file "$XERR"
+  unset NMG_REQUIRED
+  local NMDDNS_REQUIRED="99.0.0"
+
+  (. "${NMDDNS}" 2>/dev/null) &&
+    xtest::fail "FATAL: ${NMDDNS} loaded when NMDDNS_REQUIRED=${NMDDNS_REQUIRED}"
+
+  shtest::log "  Version enforcement working"
+}
+
+xmain() { # <args>
+  local XNOFILE="$TEST_OUT/no-file" XFILE="$TEST_OUT/ddns file"
+  local NMDDNS=${NMDDNS:-${NMUTILS}/ddns-functions}
+
+  xload_script "${NMDDNS}"
+
+  test_version
 
   xtest::run_tests "ddns-functions Test Summary" "$@"
 
-  [[ ${IFS} == - ]] || xtest::err "Error: IFS was modified (now '${IFS-}')"
-
   # cleanup
-  xrm "$XFILE" "$XLOG" "$XERR"
-  exec 4>&-
-
-  return 0
+  xrm "$XFILE"
 }
 
-(main "$@")
-# shellcheck disable=SC2181
-[[ $? -ne 0 ]] && xwrap_cleanup
+xstart "$@"
 
 # Local Variables:
 # mode: sh
diff --git a/test/dhclient-prefix-test b/test/dhclient-prefix-test
--- a/test/dhclient-prefix-test
+++ b/test/dhclient-prefix-test
@@ -6,64 +6,9 @@
 #
 # shellcheck disable=SC2034,SC1090,SC2123
 
-# load common.conf
-TEST_COMMON=${TEST_COMMON:-conf/common.conf}
-{ [[ -r ${TEST_COMMON} ]] && . "${TEST_COMMON}"; } ||
-  { echo >&2 "Unable to load ${TEST_COMMON}"; exit 2; }
-
-{ [[ ${XTEST_SETUP} ]] && . "${XTEST_SETUP}"; } ||
-  { echo >&2 "Unable to load xtest_setup"; exit 2; }
-
-[[ $EUID == 0 ]] && xtest::fail "Never run as root!"
-
-_CONF_FILE="$NMCONF/ipv6-prefix-wan0.conf"
-
-# NMCONF/ipv6-prefix-wan0.conf must exist
-[ -r "${_CONF_FILE}" ] ||
-  xtest::fail "Please create ${_CONF_FILE}"
-
-_TEST_SCRIPT="${SRC_ROOT}/sbin/dhclient-ipv6-prefix"
-
-# load all functions
-[ -r "${_TEST_SCRIPT}" ] ||
-  xtest::fail "${_TEST_SCRIPT} not found!"
-
-# ensure includes pass parse test
-shtest::parse "${_TEST_SCRIPT}" || shtest::fatal
-
-# less noise
-export NMG_TAG=''
-
-# these tests require MOCK_ECHO=1 to check command actions
-export MOCK_ECHO=1
-
-# need output directory
-[[ $TEST_OUT && -d $TEST_OUT ]] || xtest::fail "\$TEST_OUT is unset/missing!"
-XLOG="$TEST_OUT/prefix-script.log" XERR="$TEST_OUT/prefix-script.err"
-
-xwrap() {
-  local cmd=${1-}
-  [[ ${cmd} ]] || xtest::fail "xwrap: missing <cmd>"
-  shift
-  "${cmd}" &>"${XERR}" 4>"${XLOG}" "$@"
-}
-
-xrm() {
-  [[ ${1-} ]] || return 0
-  command -p rm -f "$@"
-}
-
-xwrap_cleanup() {
-  local rc=$?
-  [[ -e ${XERR} ]] && { command -p cat "${XERR}"; xrm "${XERR}"; }
-  [[ -e ${XLOG} ]] && { command -p cat "${XLOG}"; xrm "${XLOG}"; }
-  exit ${rc}
-}
-
-read_value() { # <var> (<stdin)
-  local IFS; unset IFS
-  read -r -d '' "$1" || :
-}
+NMG_XTEST=${NMG_XTEST:-conf/nmg_xtest}
+{ [[ -r ${NMG_XTEST} ]] && . "${NMG_XTEST}"; } ||
+  { echo >&2 "Unable to load ${NMG_XTEST}"; exit 2; }
 
 xtest::group1::life() {
   local var CUR_TIME base_time
@@ -171,7 +116,7 @@ xtest::group1::prefix() {
   Lans=() Reserved=()
   xwrap ipv6_lan_node_load "brx" "64"
   xtest P24 t "(<bad-site>) - returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	ERR: nmg::2dec: invalid <value> '0xbogus'
 	ERR: brx config error, invalid LAN_SITE 'bogus'
 	EOF
@@ -348,7 +293,7 @@ xtest::group2::addr() {
 
   xwrap ipv6_add_addr br0 "2001:db8:100::1/64"
   xtest A1 t "(<addr>) - returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Adding 2001:db8:100::1/64 to br0
 	${NMG_IP} => ip -6 addr add 2001:db8:100::1/64 dev br0
 	EOF
@@ -364,7 +309,7 @@ xtest::group2::addr() {
 
   xwrap ipv6_add_addr br0 "2001:db8:100::1/64"
   xtest A2 t "(<addr> <lifetimes set>) - returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Adding 2001:db8:100::1/64 to br0
 	${NMG_IP} => ip -6 addr add 2001:db8:100::1/64 dev br0 valid_lft 180 preferred_lft 60
 	EOF
@@ -379,7 +324,7 @@ xtest::group2::addr() {
 
   xwrap ipv6_del_addr br0 "fdc0:4455:b240::1/64"
   xtest A11 t "(<addr>) - returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Removing fdc0:4455:b240::1/64 from br0
 	${NMG_IP} => ip -6 addr del fdc0:4455:b240::1/64 dev br0
 	EOF
@@ -422,13 +367,13 @@ xtest::group3::lan() {
   new_ip6_prefix="2001:db8:100::/56" new_iaid="88:99"
   xwrap ipv6_start
   xtest L2 t "(<br0,id1>) - returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Adding 2001:db8:100:0:32fb:93c5:6555:845a/63 to br0
 	${NMG_IP} => ip -6 addr add 2001:db8:100:0:32fb:93c5:6555:845a/63 dev br0 valid_lft 180 preferred_lft 60
 	${NMG_RADVD_TRIGGER} => radvd triggered
 	EOF
   ftest L2f "$out" " - adds address"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	inet6:2001:db8:100:0:32fb:93c5:6555:845a/63
 	valid-life:240
 	pref-life:120
@@ -439,13 +384,13 @@ xtest::group3::lan() {
   new_ip6_prefix="2001:db8:200::/56" new_iaid="11:22"
   xwrap ipv6_start
   xtest L3 t "(<br0,id2>) - returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Adding 2001:db8:200:0:32fb:93c5:6555:845a/63 to br0
 	${NMG_IP} => ip -6 addr add 2001:db8:200:0:32fb:93c5:6555:845a/63 dev br0 valid_lft 180 preferred_lft 60
 	${NMG_RADVD_TRIGGER} => radvd triggered
 	EOF
   ftest L3f "$out" " - adds address"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	inet6:2001:db8:200:0:32fb:93c5:6555:845a/63
 	valid-life:240
 	pref-life:120
@@ -456,7 +401,7 @@ xtest::group3::lan() {
   WAN_LAN_INTFS="brx br0"
   xwrap ipv6_start
   xtest L4 t "(<brx br0>) - returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	ERR: nmg::create_ip6_host: Unable to determine an auto host-part for interface brx
 	Adding 2001:db8:200:0:32fb:93c5:6555:845a/63 to br0
 	${NMG_IP} => ip -6 addr add 2001:db8:200:0:32fb:93c5:6555:845a/63 dev br0 valid_lft 180 preferred_lft 60
@@ -472,7 +417,7 @@ xtest::group3::lan() {
 
   xwrap ipv6_start
   xtest L5 t "(<br1>) - returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Replacing 2001:db8:200:2:32fb:93c5:555:1/64 on br1
 	${NMG_IP} => ip -6 addr replace 2001:db8:200:2:32fb:93c5:555:1/64 dev br1
 	Adding 2001:db8:200:0:32fb:93c5:6555:845a/63 to br0
@@ -507,7 +452,7 @@ xtest::group3::lan() {
 
   xwrap ipv6_start
   xtest L6 t "(<br1>) - returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Removing 2001:db8:100:2:32fb:93c5:555:1/64 from br1
 	${NMG_IP} => ip -6 addr del 2001:db8:100:2:32fb:93c5:555:1/64 dev br1
 	Replacing 2001:db8:200:2:32fb:93c5:555:1/64 on br1
@@ -541,7 +486,7 @@ xtest::group3::lan() {
   new_ip6_prefix="2001:db8:100::/56" new_iaid="88:99"
   xwrap ipv6_start
   xtest L7 t "(<br1>) - returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Replacing 2001:db8:100:2:32fb:93c5:555:1/64 on br1
 	${NMG_IP} => ip -6 addr replace 2001:db8:100:2:32fb:93c5:555:1/64 dev br1
 	Adding 2001:db8:100:0:32fb:93c5:6555:845a/63 to br0
@@ -579,7 +524,7 @@ xtest::group3::lan() {
 
   xwrap ipv6_depref
   xtest L11 t "(<88:99>) - returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Adding 2001:db8:100:0:32fb:93c5:6555:845a/63 to br0
 	${NMG_IP} => ip -6 addr replace 2001:db8:100:0:32fb:93c5:6555:845a/63 dev br0 valid_lft 180 preferred_lft 0
 	Changing 2001:db8:100:2:32fb:93c5:555:1/64 on br1
@@ -594,14 +539,14 @@ xtest::group3::lan() {
 	${NMG_RADVD_TRIGGER} => radvd triggered
 	EOF
   ftest L11f "$out" " - sets address lifetime 0, removes from dns"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	inet6:2001:db8:100:0:32fb:93c5:6555:845a/63
 	valid-life:180
 	pref-life:0
 	life-start:3000
 	EOF
   shtest::check_file L11i "$state1" "$out" " - creates br0 88:99 state file"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	inet6:2001:db8:100:2:32fb:93c5:555:1/64
 	valid-life:180
 	pref-life:0
@@ -617,7 +562,7 @@ xtest::group3::lan() {
 
   xwrap ipv6_stop
   xtest L21 t "(<88:99>) - returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Removing 2001:db8:100:2:32fb:93c5:555:1/64 from br1
 	${NMG_IP} => ip -6 addr del 2001:db8:100:2:32fb:93c5:555:1/64 dev br1
 	Setting home.example.test AAAA to 2001:db8:200:2:32fb:93c5:555:1
@@ -641,7 +586,7 @@ xtest::group3::lan() {
 
   xwrap ipv6_prefix_flush
   xtest L31 t "() - returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Removing 2001:db8:200:2:32fb:93c5:555:1/64 from br1
 	${NMG_IP} => ip -6 addr del 2001:db8:200:2:32fb:93c5:555:1/64 dev br1
 	Removing home.example.test AAAA
@@ -677,64 +622,26 @@ xtest::group3::wan() {
 
 }
 
-load_script() {
-
-  shtest::title "Loading script"
-
-  (xwrap . "${_TEST_SCRIPT}"; echo >>"$XLOG" "loaded $?")
-  ftest load "loaded 0" " - script loads without error"
-  shtest::last_check_ok || xtest::fail "Loading '${_TEST_SCRIPT}' failed"
-
-  # load script in current subshell
-  xwrap . "${_TEST_SCRIPT}"
-
-  [[ ${WAN_LAN_INTFS} ]] ||
-    xtest::fail "Config file '${_CONF_FILE}' failed to load"
-
-  # reset path
-  PATH=''
-}
-
-main() {
-  local XFILE="$TEST_OUT/prefix-script file" IFS=-
+xmain() {
+  local XFILE="$TEST_OUT/prefix-script file" WAN_LAN_INTFS=''
   local TEST_RADVD_TRIGGER="$TEST_BIN/dummy-mock"
-  local -x DUMMY_MOCK_OUTPUT="radvd triggered"
+  local -x DUMMY_MOCK_OUTPUT="radvd triggered" interface=wan0
 
   # disable helper so we get nsupdate results
   local TEST_DDNS_HELPER=''
 
-  # restrict use of external commands (except those defined in config)
-  PATH=''
+  xload_script "${SRC_ROOT}/sbin/dhclient-ipv6-prefix"
 
-  # reset (in subshell)
-  shtest::reset
-
-  # fd 4 used for logger
-  export nmg_log_stderr=4
-  exec 4>&2
-
-  # required environment
-  export interface=wan0
-
-  shtest::reg_file "$XLOG"
-  shtest::reg_file "$XERR"
-
-  load_script
+  [[ ${WAN_LAN_INTFS} ]] ||
+    xtest::fail "Config file failed to load"
 
   xtest::run_tests "dhclient-ipv6-prefix Test Summary" "$@"
 
-  [[ ${IFS} == - ]] || xtest::err "Error: IFS was modified (now '${IFS-}')"
-
   # cleanup
-  xrm "$XFILE" "$XLOG" "$XERR"
-  exec 4>&-
-
-  return 0
+  xrm "$XFILE"
 }
 
-(main "$@")
-# shellcheck disable=SC2181
-[[ $? -ne 0 ]] && xwrap_cleanup
+xstart "$@"
 
 # Local Variables:
 # mode: sh
diff --git a/test/general-test b/test/general-test
--- a/test/general-test
+++ b/test/general-test
@@ -5,72 +5,12 @@
 #
 # shellcheck disable=SC2034,SC1090,SC2123
 
-# load common.conf
-TEST_COMMON=${TEST_COMMON:-conf/common.conf}
-{ [[ -r ${TEST_COMMON} ]] && . "${TEST_COMMON}"; } ||
-  { echo >&2 "Unable to load ${TEST_COMMON}"; exit 2; }
-
-{ [[ ${XTEST_SETUP} ]] && . "${XTEST_SETUP}"; } ||
-  { echo >&2 "Unable to load xtest_setup"; exit 2; }
-
-[[ $EUID == 0 ]] && xtest::fail "Never run as root!"
-
-NMG=${NMG:-${NMUTILS}/general-functions}
-
-# ensure includes pass parse test
-shtest::parse "${NMG}" || shtest::fatal
-
-# verify required
-NMG_REQUIRED="99.0.0"
-
-(. "${NMG}" 2>/dev/null &&
-   xtest::fail "FATAL: ${NMG} loaded when NMG_REQUIRED=${NMG_REQUIRED}" ||
-     :) || exit 1
+NMG_XTEST=${NMG_XTEST:-conf/nmg_xtest}
+{ [[ -r ${NMG_XTEST} ]] && . "${NMG_XTEST}"; } ||
+  { echo >&2 "Unable to load ${NMG_XTEST}"; exit 2; }
 
 # min-version for tests
 NMG_REQUIRED="1.5.6"
-
-# less noise
-export NMG_TAG=''
-
-. "${NMG}" || exit 1
-
-# don't let general-functions use external commands
-# (except those defined in config)
-PATH=''
-
-# these tests require MOCK_ECHO=1 to check command actions
-export MOCK_ECHO=1
-
-# need output directory
-[[ $TEST_OUT && -d $TEST_OUT ]] || xtest::fail "\$TEST_OUT is unset/missing!"
-# realpath test requires TEST_OUT to be relative
-[[ $TEST_OUT =~ ^/ ]] && xtest::fail "\$TEST_OUT must be relative!"
-XLOG="$TEST_OUT/general.log" XERR="$TEST_OUT/general.err"
-
-xwrap() {
-  local cmd=${1-}
-  [[ ${cmd} ]] || xtest::fail "xwrap: missing <cmd>"
-  shift
-  "${cmd}" &>"${XERR}" 4>"${XLOG}" "$@"
-}
-
-xrm() {
-  [[ ${1-} ]] || return 0
-  command -p rm -f "$@"
-}
-
-xwrap_cleanup() {
-  local rc=$?
-  [[ -e ${XERR} ]] && { command -p cat "${XERR}"; xrm "${XERR}"; }
-  [[ -e ${XLOG} ]] && { command -p cat "${XLOG}"; xrm "${XLOG}"; }
-  exit ${rc}
-}
-
-read_value() { # <var> (<stdin)
-  local IFS; unset IFS
-  read -r -d '' "$1" || :
-}
 
 xtest::group1::log() {
   local nmg_show_debug=''
@@ -228,7 +168,7 @@ xtest::group2::err() {
 xtest::group3::prop() {
   local var=''
   local dict
-  read_value dict <<- EOF
+  xread_value dict <<- EOF
 	first:val
 	empty:
 	item:value
@@ -949,7 +889,7 @@ xtest::group3::file() {
   ftest F5f "" " - should not log"
   shtest::check_file F5c "$XFILE" "content" " - file should have content"
 
-  read_value var <<- EOF
+  xread_value var <<- EOF
 	content
 	  second line
 	EOF
@@ -1473,33 +1413,34 @@ xtest::group4::config() {
         " - logs error"
 }
 
-main() {
-  local XNOFILE="$TEST_OUT/no-file" XFILE="$TEST_OUT/general file" IFS=-
+test_version() {
+  local NMG_REQUIRED="99.0.0" nmg_log_stderr=1
 
-  # reset (in subshell)
-  shtest::reset
+  shtest::title "Check version requirements"
 
-  # fd 4 used for logger
-  export nmg_log_stderr=4
-  exec 4>&2
+  (. "${NMG}" 2>/dev/null) &&
+    xtest::fail "  FATAL: ${NMG} loaded when NMG_REQUIRED=${NMG_REQUIRED}"
 
-  shtest::reg_file "$XLOG"
-  shtest::reg_file "$XERR"
+  shtest::log "  Version enforcement working"
+}
+
+xmain() {
+  local XNOFILE="$TEST_OUT/no-file" XFILE="$TEST_OUT/general file"
+  local NMG=${NMG:-${NMUTILS}/general-functions}
+
+  xload_script "${NMG}"
+
+  test_version
 
   xtest::run_tests "general-functions Test Summary" "$@"
 
-  [[ ${IFS} == - ]] || xtest::err "Error: IFS was modified (now '${IFS-}')"
-
   # cleanup
-  xrm "$XFILE" "$XLOG" "$XERR"
-  exec 4>&-
+  xrm "$XFILE"
 
   return 0
 }
 
-(main "$@")
-# shellcheck disable=SC2181
-[[ $? -ne 0 ]] && xwrap_cleanup
+xstart "$@"
 
 # Local Variables:
 # mode: sh
diff --git a/test/ipv6-prefix-test b/test/ipv6-prefix-test
--- a/test/ipv6-prefix-test
+++ b/test/ipv6-prefix-test
@@ -6,58 +6,9 @@
 #
 # shellcheck disable=SC2034,SC1090,SC2123
 
-# load common.conf
-TEST_COMMON=${TEST_COMMON:-conf/common.conf}
-{ [[ -r ${TEST_COMMON} ]] && . "${TEST_COMMON}"; } ||
-  { echo >&2 "Unable to load ${TEST_COMMON}"; exit 2; }
-
-{ [[ ${XTEST_SETUP} ]] && . "${XTEST_SETUP}"; } ||
-  { echo >&2 "Unable to load xtest_setup"; exit 2; }
-
-[[ $EUID == 0 ]] && xtest::fail "Never run as root!"
-
-_TEST_SCRIPT="${SRC_ROOT}/etc/NetworkManager/dispatcher.d/08-ipv6-prefix"
-
-# load all functions
-[ -r "${_TEST_SCRIPT}" ] ||
-  xtest::fail "${_TEST_SCRIPT} not found!"
-
-# ensure includes pass parse test
-shtest::parse "${_TEST_SCRIPT}" || shtest::fatal
-
-# less noise
-export NMG_TAG=''
-
-# these tests require MOCK_ECHO=1 to check command actions
-export MOCK_ECHO=1
-
-# need output directory
-[[ $TEST_OUT && -d $TEST_OUT ]] || xtest::fail "\$TEST_OUT is unset/missing!"
-XLOG="$TEST_OUT/prefix.log" XERR="$TEST_OUT/prefix.err"
-
-xwrap() {
-  local cmd=${1-}
-  [[ ${cmd} ]] || xtest::fail "xwrap: missing <cmd>"
-  shift
-  "${cmd}" &>"${XERR}" 4>"${XLOG}" "$@"
-}
-
-xrm() {
-  [[ ${1-} ]] || return 0
-  command -p rm -f "$@"
-}
-
-xwrap_cleanup() {
-  local rc=$?
-  [[ -e ${XERR} ]] && { command -p cat "${XERR}"; xrm "${XERR}"; }
-  [[ -e ${XLOG} ]] && { command -p cat "${XLOG}"; xrm "${XLOG}"; }
-  exit ${rc}
-}
-
-read_value() { # <var> (<stdin)
-  local IFS; unset IFS
-  read -r -d '' "$1" || :
-}
+NMG_XTEST=${NMG_XTEST:-conf/nmg_xtest}
+{ [[ -r ${NMG_XTEST} ]] && . "${NMG_XTEST}"; } ||
+  { echo >&2 "Unable to load ${NMG_XTEST}"; exit 2; }
 
 xtest::group3::wan() {
 
@@ -126,7 +77,7 @@ xtest::group3::lan() {
   echo "inet6:2001:db8:100:2:32fb:93c5:555:1/64" > "$state1"
   xwrap ipv6_lan_start
   xtest L1 t "() - returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Replacing 2001:db8:100:2:32fb:93c5:555:1/64 on br1
 	${NMG_IP} => ip -6 addr replace 2001:db8:100:2:32fb:93c5:555:1/64 dev br1
 	Setting wan1.example.test AAAA to 2001:db8:100:2:32fb:93c5:555:1
@@ -148,7 +99,7 @@ xtest::group3::lan() {
   CUR_TIME=3200
   xwrap ipv6_lan_start
   xtest L2 t "() - returns true"
-  read_value out <<-EOF
+  xread_value out <<-EOF
 	Replacing 2001:db8:100:2:32fb:93c5:555:1/64 on br1
 	${NMG_IP} => ip -6 addr replace 2001:db8:100:2:32fb:93c5:555:1/64 dev br1
 	Replacing 2001:db8:200:2:32fb:93c5:555:1/64 on br1
@@ -187,58 +138,24 @@ xtest::group3::lan() {
   unset WAN_LAN_INTFS WAN_REQUIRE_IP4 WAN_DHCLIENT_OPTIONS
 }
 
-load_script() {
-
-  shtest::title "Loading script"
-
-  (xwrap . "${_TEST_SCRIPT}" dummy general; echo >>"$XLOG" "loaded $?")
-  ftest load "loaded 0" " - script loads without error"
-  shtest::last_check_ok || xtest::fail "Loading '${_TEST_SCRIPT}' failed"
-
-  # load script in current subshell
-  xwrap . "${_TEST_SCRIPT}" dummy general
-
-  # reset PATH
-  PATH=''
-}
-
-main() {
-  local XFILE="$TEST_OUT/prefix file" IFS=-
+xmain() {
+  local XFILE="$TEST_OUT/prefix file"
   local TEST_RADVD_TRIGGER="$TEST_BIN/dummy-mock"
   local TEST_DHSCRIPT="$TEST_BIN/dummy-mock"
 
   # disable helper so we get nsupdate results
   local TEST_DDNS_HELPER=''
 
-  # restrict use of external commands (except those defined in config)
-  local PATH=''
-
-  # reset (in subshell)
-  shtest::reset
-
-  # fd 4 used for logger
-  export nmg_log_stderr=4
-  exec 4>&2
-
-  shtest::reg_file "$XLOG"
-  shtest::reg_file "$XERR"
-
-  load_script
+  xload_script "${SRC_ROOT}/etc/NetworkManager/dispatcher.d/08-ipv6-prefix" \
+               dummy general
 
   xtest::run_tests "08-ipv6-prefix Test Summary" "$@"
 
-  [[ ${IFS} == - ]] || xtest::err "Error: IFS was modified (now '${IFS-}')"
-
   # cleanup
-  xrm "$XFILE" "$XLOG" "$XERR"
-  exec 4>&-
-
-  return 0
+  xrm "$XFILE"
 }
 
-(main "$@")
-# shellcheck disable=SC2181
-[[ $? -ne 0 ]] && xwrap_cleanup
+xstart "$@"
 
 # Local Variables:
 # mode: sh
