NMDDNS v1.3.7 - added NMDDNS_VERSION/REQUIRED

diff --git a/test/ddns-test b/test/ddns-test
--- a/test/ddns-test
+++ b/test/ddns-test
@@ -18,11 +18,31 @@ NMDDNS="${NMDDNS:-${NMUTILS}/ddns-functions}"
 # ensure includes pass parse test
 shtest::parse "${NMDDNS}" || shtest::fatal
 
+# verify required
+NMG_REQUIRED="99.0.0"
+
 # shellcheck source=/dev/null
-. "${NMDDNS}"
+(. "${NMDDNS}" 2>/dev/null && {
+  echo >&2 "FATAL: ${NMDDNS} loaded when NMG_REQUIRED=${NMG_REQUIRED}"
+  exit 1
+} || :) || exit 1
+
+unset NMG_REQUIRED
+NMDDNS_REQUIRED="99.0.0"
+# shellcheck source=/dev/null
+(. "${NMDDNS}" 2>/dev/null && {
+  echo >&2 "FATAL: ${NMDDNS} loaded when NMDDNS_REQUIRED=${NMDDNS_REQUIRED}"
+  exit 1
+} || :) || exit 1
+
+# min-version for tests
+NMDDNS_REQUIRED="1.3.7"
 
 # less noise
 export NMG_TAG=''
+
+# shellcheck source=/dev/null
+. "${NMDDNS}" || exit 1
 
 # these tests require MOCK_ECHO=1 to check command actions
 export MOCK_ECHO=1
