Include shtest v1.0

diff --git a/test/shtest_setup b/test/shtest_setup
--- a/test/shtest_setup
+++ b/test/shtest_setup
@@ -1,6 +1,6 @@
 # vim:set ft=sh et sw=2 ts=2:
 #
-# shtest v1.3.0 - Shell script testing functions
+# shtest v1.0.0 - Shell script testing functions
 # Author: Scott Shambarger <devel@shambarger.net>
 #
 # Copyright (C) 2021 Scott Shambarger
@@ -18,171 +18,130 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
-# === Instructions for use ===
+# === Public Function Reference ===
 #
-#   Source this file somewhere in your test program:
+#   shtest::verbose [ <level> ]
 #
-#     . shtest_setup
+#     Displays test descriptions even when test passes.
 #
-#   Set some options
+#   shtest::quiet
 #
-#     shtest::verbose
-#     shtest::strict trace
-#     shtest::global_whitelist "my_test_func_*"
-#     shtest::save_env myenv
+#     Display only summary report.
 #
-#   Perform a parse test on source
+#   shtest::log <msg>
 #
-#     shtest::parse "my_funcs.sh" || shtest::fatal "parse failed"
+#     Writes <msg> to shtest message stream (may be muted).
 #
-#   Display some titles, set a logging prefix
+#   shtest::add_focus <id/pattern>
 #
-#     shtest::title "Command Tests"
-#     shtest::prefix "my_command() "
+#     Show only tests matching <id> or <pattern> (*/? wildcards).
 #
-#   Run some tests
+#   shtest::strict [ "trace" ]
 #
-#     my_command -v var "a value" 2>outfile
-#     shtest::check_result T1 t "with -v, returns true"
-#     shtest::check_var T2 "a value" "\$var == 'a value'"
-#     shtest::check_value T3 othervar "zzz" "\$othervar == 'zzz'"
-#     shtest::check_array T4 avar aref "array avar matches aref"
-#     shtest::check_file T5 "outfile" "command err" "command writes stderr"
+#     Enables 'set -eEu' bash options, any failures a captured and fail
+#     the next shtest::check_*.  "trace" enables backtrace on failure.
 #
-#     shtest::whitelist "my_command"
-#     var=$(my_command 2>&1 "fail arg")
-#     shtest::check_result T6 "with 'fail arg', returns 2"
-#     shtest::check_var T7 "command failed" "stderr contains 'command failed'"
-#     shtest::last_check_ok && more_tests
+#   shtest::global_whitelist <pattern>
 #
-#   Display final report
+#     Strict mode ignores failure of any function matching <pattern>
+#     Useful to allow functions in <pattern> to call functions that
+#     fail without triggering strict-mode failures.
 #
-#     shtest::check_env ENV myenv "check environment"
-#     shtest::final_report
+#   shtest::whitelist <pattern>
 #
-#   Reset and counters/options for a new run
+#     As global_whitelist, but only until next shtest::check_* called.
 #
-#     shtest::reset
+#   shtest::parse <file>
 #
-#  === Public function reference ===
+#     Runs a bash parse test of <file>, displays errors to stderr,
+#     returns true/false.
 #
-#     shtest::verbose [ <level> ]
-#       Displays test descriptions even when test passes
+#   shtest::cleanup
 #
-#     shtest::strict [ "trace" ]
-#       Enables 'set -eEu' bash options, any failures a captured and fail
-#       the next shtest::check_*.  "trace" enables backtrace on failure.
+#     Removes all global environment variables and traps set by shtest
+#     Call before exit to avoid warnings on unexpected exit.
 #
-#     shtest::global_whitelist <pattern>
-#       Strict mode ignores failure of any function matching <pattern>
-#       Useful to allow functions in <pattern> to call functions that
-#       fail without triggering strict-mode failures.
+#   shtest::fatal [ <msg> [ <backtrace-skip> ] ]
 #
-#     shtest::whitelist <pattern>
-#       As global_whitelist, but only until next shtest::check_* called
+#     Exits 1 with text <msg>, optionally printing backtrace (skipping
+#     <backtrace-skip> calls if > 0).
 #
-#     shtest::parse <file>
-#       Runs a bash parse test of <file>, displays errors to stderr,
-#       returns true/false
+#   shtest::title <title>
 #
-#     shtest::cleanup
-#       Removes all global environment variables and traps set by shtest
+#     Prints a new section header with <title> (resets <prefix>)
 #
-#     shtest::fatal [ <msg> [ <backtrace-skip> ] ]
-#       Exits 1 with text <msg>, optionally printing backtrace skipping
-#       <backtrace-skip> calls
+#   shtest::prefix [ <prefix> ]
 #
-#     shtest::title <title>
-#       Prints a new section header with <title>
+#     Adds <prefix> before all test report <descrition>s (resets if empty).
 #
-#     shtest::prefix [ <prefix> ]
-#       Adds <prefix> before all test report <descrition>s (resets if empty)
+#   shtest::check_result <id> <ref> [ <description> ]
 #
-#     shtest::check_result <id> <ref> [ <description> ]
-#       Checks $? (most recent function return) against <ref>, which can be:
-#         "t" - $? == 0
-#         "f" - $? != 0
-#         # - $? == #
-#       Displayes "<id> OK", or "<id> FAIL | <desciption>" if failure,
-#       including expected vs actual results.
+#     Checks $? (most recent function return) against <ref>, which can be:
+#       "t" - $? == 0
+#       "f" - $? != 0
+#       # - $? == #
+#     Displayes "<id> OK", or "<id> FAIL | <desciption>" if failure,
+#     including expected vs actual results.
 #
-#     shtest::check_value <id> <varname> [ <ref> [ <desc> ] ]
-#       Checks value of variable named <varname> against <ref>, and
-#       displays "<id> OK" or "<id> FAIL | <description>" including
-#       expected vs actual value.
+#   shtest::check_value <id> <varname> [ <ref> [ <desc> ] ]
 #
-#     shtest::check_var <id> [ <ref> [ <desc> ] ]
-#       Shortcut for shtest::check_value <id> "var"...
+#     Checks value of variable named <varname> against <ref>, and
+#     displays "<id> OK" or "<id> FAIL | <description>" including
+#     expected vs actual value.
 #
-#     shtest::check_array <id> <varname> <refname> [ <desc> ]
-#       Checks value of array elements in array named <aname> with those in
-#       array named <refname>, displays "<id> OK" or
-#       "<id> FAIL | <descr>" including expected vs actual value.
+#   shtest::check_var <id> [ <ref> [ <desc> ] ]
 #
-#     shtest::check_file <id> <filename> <contents> [ <desc> ]
-#       Checks contents of <filename> against <contents>, displays
-#       "<id> OK" or "<id> FAIL | <desc>" including expected vs actual
-#       contents
+#     Shortcut for shtest::check_value <id> "var"...
 #
-#     shtest::reg_file [ <filename> ]
-#       Register <filename> for shtest::check_reg_files tests.
-#       Without <filename>, echos list of registered filenames
+#   shtest::check_array <id> <varname> <refname> [ <desc> ]
 #
-#     shtest::dereg_file <filename>
-#       Remove <filename> from shtest::check_reg_files tests
+#     Checks value of array elements in array named <aname> with those in
+#     array named <refname>, displays "<id> OK" or
+#     "<id> FAIL | <descr>" including expected vs actual value.
 #
-#     shtest::check_reg_files <id> <desc> [ <fileX_contents>... ]
-#       Checks contents of files registered with shtest::reg_file
-#       in order against <fileX_contents>, displays "<id> OK" or
-#       <id> FAIL | <desc>" including expected vs actual for first
-#       file with mis-matched content.
+#   shtest::check_file <id> <filename> <contents> [ <desc> ]
 #
-#     shtest::last_check_ok
-#       Returns true/false based on the result of the last shtest:check_*
+#     Checks contents of <filename> against <contents>, displays
+#     "<id> OK" or "<id> FAIL | <desc>" including expected vs actual
+#     contents.
 #
-#     shtest::final_report
-#       Prints final count of tests, with any fail counts.  Removes
-#       any internal state, globals (you must call shtest::reset before
-#       running any more tests)
+#   shtest::reg_file [ <filename> ]
 #
-#     shtest::reset
-#       Re-initializes shtest for a new run.  This is called
-#       automatically when shtest_setup is sourced.
+#     Register <filename> for shtest::check_reg_files tests.
+#     Without <filename>, echos list of registered filenames.
 #
-#     shtest::save_env <varname>
-#       Store current shell variable names in <varname>
+#   shtest::dereg_file <filename>
 #
-#     shtest::check_env <id> <varname> [ <desc> ]
-#       Checks shell variables against those stored in <varname>, and
-#       displays "<id> OK" or "<id> FAIL | <description>" including
-#       a list of new variables added to the environment.
+#     Remove <filename> from shtest::check_reg_files tests.
 #
-# === Useful tips ===
+#   shtest::check_reg_files <id> <desc> [ <fileX_contents>... ]
 #
-#   o All output is printed to stderr using file descriptor 88, so it's best
-#     not to use that in your tests
+#     Checks contents of files registered with shtest::reg_file
+#     in order against <fileX_contents>, displays "<id> OK" or
+#     <id> FAIL | <desc>" including expected vs actual for first
+#     file with mis-matched content.
 #
-#   o All test <id>'s must be unique... duplicates cause the test to exit.
+#   shtest::last_check_ok
 #
-#   o Aliases are useful to ease typing, eg:
+#     Returns true/false based on the result of the last shtest:check_*
 #
-#       shopt -s expand_aliases
-#       alias xtest=shtest::check_result
-#       xtest T1 t "should return true"
+#   shtest::summary_report
 #
-#   o Strict mode can be tricky to use correctly, make sure you add
-#     any parent functions that test failures to the global_whitelist, eg:
+#     Prints count of tests, with any fail counts.
 #
-#       shtest::global_whitelist "my_test_func_*"
-#       my_test_func_1() {
-#         false
-#         shtest::check_result T1 f "should fail"
-#       }
+#   shtest::reset
 #
-#   o Strict mode exits when unbound variables are referenced, so make
-#     sure you don't "2>/dev/null" functions that might cause them, or
-#     you may miss the full description (shtest will still display
-#     backtrace to help though).
+#     Re-initializes shtest for a new run.
+#
+#   shtest::save_env <varname>
+#
+#     Store current shell variable names in <varname>.
+#
+#   shtest::check_env <id> <varname> [ <desc> ]
+#
+#     Checks shell variables against those stored in <varname>, and
+#     displays "<id> OK" or "<id> FAIL | <description>" including
+#     a list of new variables added to the environment.
 #
 # shellcheck shell=bash
 
@@ -231,11 +190,6 @@ shtest::_init_globals() {
   exec 88>&2
 }
 
-shtest::_init() {
-  shtest::cleanup
-  shtest::_init_globals
-}
-
 # returns 1 if strict mode failed
 shtest::_reset_state() {
   _SHTEST_STATE[7]='' _SHTEST_WHITELIST=()
@@ -249,12 +203,18 @@ shtest::_reset_state() {
 }
 
 shtest::_log() { # <msg>
+  # focus mutes _log too
+  [[ ${_SHTEST_STATE[8]} == 1 ]] && return 0
+  printf >&88 "%s\n" "$*"
+}
+
+shtest::log() { # <msg>
   [[ ${_SHTEST_STATE[0]+set} == set ]] || {
-    echo >&2 "FATAL: You must call shtest::reset after shtest::final_report"
+    echo >&2 "FATAL: You must call shtest::reset after shtest::cleanup"
     exit 1
   }
   [[ ${_SHTEST_STATE[8]} ]] && return 0
-  printf >&88 "%s\n" "$*"
+  shtest::_log "$*"
 }
 
 shtest::_fmtlog() { # <format> <args>
@@ -263,7 +223,7 @@ shtest::_fmtlog() { # <format> <args>
   # shellcheck disable=SC2059
   printf -v msg "$1" "${@:2}" ||
     shtest::fatal "shtest::_fmtlog() bad format: $1" 3
-  shtest::_log "${msg}"
+  shtest::log "${msg}"
 }
 
 # assumes lowest two stack frames can be skipping in backtrace
@@ -271,7 +231,7 @@ shtest::_backtrace() { # <skip>
   local i depth=${#FUNCNAME[@]} func lno src skip
   printf 2>/dev/null -v skip "%d" "${1-1}" || skip=1
   [[ ${skip} -lt 1 ]] && skip=1
-  shtest::_log "Backtrace:"
+  shtest::log "Backtrace:"
   for (( i=skip; i < depth; i++ )); do
     func=${FUNCNAME[${i}]}
     lno=${BASH_LINENO[(( i - 1 ))]}
@@ -287,9 +247,9 @@ shtest::fatal() { # <msg> [ <backtrace-skip> ]
   _SHTEST_FATAL=1
   _SHTEST_STATE[8]= # unmute
   if [[ ${1-} ]]; then
-    shtest::_log "FATAL: $1"
+    shtest::log "FATAL: $1"
   else
-    shtest::_log "Fatal error, quitting..."
+    shtest::log "Fatal error, quitting..."
   fi
   [[ ${2-} ]] && shtest::_backtrace "$2"
   shtest::cleanup
@@ -298,7 +258,6 @@ shtest::fatal() { # <msg> [ <backtrace-skip> ]
 
 shtest::_log_ok() { # <id> <description>
   local desc=''
-  # shellcheck disable=SC2034
   _SHTEST_STATE[7]=1
   [[ ${_SHTEST_STATE[3]} ]] && desc="${2:+   | ${_SHTEST_STATE[5]}}${2:-}"
   shtest::_fmtlog " %-4s OK%s" "$1" "${desc}"
@@ -312,10 +271,10 @@ shtest::_log_fail() { # <id> <description> [ <reason> | <expect> <found> ]
   local id=${1-} desc="${2:+ | ${_SHTEST_STATE[5]}}${2:-}"
   shtest::_fmtlog " %-4s FAIL%s" "${id}" "${desc}"
   if [[ ${3+set} && ${4+set} ]]; then
-    shtest::_log "      expected: ${3-}"
-    shtest::_log "         found: ${4-}"
+    shtest::log "      expected: ${3-}"
+    shtest::log "         found: ${4-}"
   elif [[ ${3+set} ]]; then
-    shtest::_log "        reason: ${3-}"
+    shtest::log "        reason: ${3-}"
   fi
   ((_SHTEST_STATE[1]++)) || :
   _SHTEST_FAILED+=("${id}")
@@ -324,10 +283,9 @@ shtest::_log_fail() { # <id> <description> [ <reason> | <expect> <found> ]
 }
 
 shtest::title() { # <title>
-  # shellcheck disable=SC2034
   _SHTEST_STATE[5]=
   shtest::_reset_state || :
-  shtest::_log $'\n'"===== $* ====="$'\n'
+  [[ $* ]] && shtest::log $'\n'"===== $* ====="$'\n'
 }
 
 shtest::prefix() { # <description-prefix>
@@ -343,9 +301,9 @@ shtest::_check_entry() { # <id> [ <desc> ]
     done
   fi
   _SHTEST_TESTLIST+=("${id}")
-  if [[ ${#_SHTEST_FOCUS[*]} != 0 ]]; then
-    [[ ${_SHTEST_FOCUS[*]} =~ (^| )"${id}"($| ) ]] && _SHTEST_STATE[8]=
-  fi
+  for tid in ${_SHTEST_FOCUS[@]+"${_SHTEST_FOCUS[@]}"}; do
+    [[ ${id} =~ ^${tid}$ ]] && { _SHTEST_STATE[8]=; break; }
+  done
   shtest::_reset_state && return 0
   shtest::_log_fail "${id}" "${desc}" "strict mode failure"
   return 1
@@ -500,10 +458,20 @@ shtest::check_reg_files() { # <id> <desc> [ <fileX_contents>... ]
   shtest::_log_ok "${id}" "${desc}"
 }
 
-shtest::add_focus() { # <id>
-  [[ ${1-} ]] || return 0
-  _SHTEST_FOCUS+=("$1")
-  _SHTEST_STATE[8]=1 # mute
+shtest::_toreg() { # <retvar> <name/pattern>
+  local pat=${2-}
+  [[ ${1-} && ${pat} ]] || return 1
+  # convert to regex
+  pat=${pat//[*]/.*}; pat=${pat//[?]/.}
+  printf -v "$1" "%s" "${pat}"
+}
+
+shtest::add_focus() { # <id/pattern>
+  local p
+  shtest::_toreg p "${1-}" || return
+  _SHTEST_FOCUS+=("${p}")
+  # mutes log/_log except during test
+  _SHTEST_STATE[8]=1
   return 0
 }
 
@@ -537,53 +505,51 @@ shtest::check_env() { # <id> <varname> [ <desc> ]
 shtest::parse() { # <file>
   local file=${1-}
   [[ ${file} ]] || {
-    shtest::_log "Usage: shtest::parse <file>"; return 1; }
+    shtest::log "Usage: shtest::parse <file>"; return 1; }
   [[ -f ${file} ]] || {
-    shtest::_log "shtest::parse(${file}) not found"; return 1; }
+    shtest::log "shtest::parse(${file}) not found"; return 1; }
   bash -n "${file}" || {
-    shtest::_log "shtest::parse(${file}) failed"; return 1; }
+    shtest::log "shtest::parse(${file}) failed"; return 1; }
 }
 
-shtest::final_report() {
+shtest::summary_report() {
+  local rc=0
   shtest::_reset_state || :
-  [[ ${_SHTEST_STATE[8]} == 2 ]] && _SHTEST_STATE[8]= # unmute
-  shtest::_log $'\n'"%%%%% FINAL REPORT %%%%%"$'\n'
+  shtest::_log $'\n'"%%%%% SUMMARY REPORT %%%%%"$'\n'
   shtest::_log "     TESTS RUN: ${_SHTEST_STATE[0]}"
   shtest::_log "  TESTS PASSED: $(( _SHTEST_STATE[0] - _SHTEST_STATE[1] ))"
   if [[ ${_SHTEST_STATE[1]} != 0 ]]; then
     local id msg
-    shtest::_log "   TESTS FAILED: ${_SHTEST_STATE[1]}"
-    msg="  FAILING TESTS:"
+    shtest::_log "  TESTS FAILED: ${_SHTEST_STATE[1]}"
+    msg="    FAILED IDS:"
     for id in "${_SHTEST_FAILED[@]}"; do
       msg+=" ${id}"
     done
     shtest::_log "${msg}"
-    shtest::_log "To run just one test, use \"X<id>\""
+    rc=1
   fi
   shtest::_log ""
-  shtest::cleanup
+  return ${rc}
 }
 
 shtest::quiet() {
-  _SHTEST_STATE[8]=2
+  # mutes all except _log
+  [[ ${_SHTEST_STATE[8]-} ]] || _SHTEST_STATE[8]=2
 }
 
 shtest::_handle_err() {
   set +eu
   local wl
-  for wl in "${_SHTEST_WHITELIST[@]}"; do
-    # shellcheck disable=SC2053
-    [[ ${FUNCNAME[1]} == ${wl} ]] && return
+  for wl in ${_SHTEST_WHITELIST[@]+"${_SHTEST_WHITELIST[@]}"}; do
+    [[ ${FUNCNAME[1]} =~ ^${wl}$ ]] && return
   done
-  for wl in "${_SHTEST_GLOBAL_WHITELIST[@]}"; do
-    # shellcheck disable=SC2053
-    [[ ${FUNCNAME[1]} == ${wl} ]] && return
+  for wl in ${_SHTEST_GLOBAL_WHITELIST[@]+"${_SHTEST_GLOBAL_WHITELIST[@]}"}; do
+    [[ ${FUNCNAME[1]} =~ ^${wl}$ ]] && return
   done
   # may be in subshell, so touch file to communicate strict failure
   touch "${_SHTEST_STATE[2]}" || :
   # rest is backtrace if requested
   [[ ${_SHTEST_STATE[6]} ]] || return 0
-  _SHTEST_STATE[8]= # unmute
   shtest::_backtrace 2
 }
 
@@ -595,9 +561,9 @@ shtest::_handle_exit() { # <$?>
   _SHTEST_STATE[8]= # unmute
   [[ ${_shtest_rc} == 0 ]] && _shtest_rc=1
   if [[ $- =~ u && ${_shtest_rc} == 1 ]]; then
-    shtest::_log "Unexpected exit, likely unbound variable"
+    shtest::log "Unexpected exit, likely unbound variable"
   else
-    shtest::_log "Unexpected exit ${_shtest_rc}"
+    shtest::log "Unexpected exit ${_shtest_rc}"
   fi
   # always show backtrace on unexpected exit
   shtest::_backtrace 2
@@ -622,11 +588,15 @@ shtest::strict() { # [ "trace" ]
 }
 
 shtest::whitelist() { # <pattern>
-  _SHTEST_WHITELIST+=("${1:-*}")
+  local p
+  shtest::_toreg p "${1-}" || return
+  _SHTEST_WHITELIST+=("${p}")
 }
 
 shtest::global_whitelist() { # <pattern>
-  _SHTEST_GLOBAL_WHITELIST+=("${1:-*}")
+  local p
+  shtest::_toreg p "${1-}" || return
+  _SHTEST_GLOBAL_WHITELIST+=("${p}")
 }
 
 shtest::verbose() { # [ <level> ]
@@ -636,7 +606,11 @@ shtest::verbose() { # [ <level> ]
 }
 
 shtest::reset() {
-  shtest::_init
+  local i state=("${_SHTEST_STATE[@]-}")
+  shtest::cleanup
+  shtest::_init_globals
+  # restore logging state
+  for i in 3 8; do _SHTEST_STATE[${i}]=${state[${i}]-}; done
 }
 
 # initialize everything
