Added MOCK_FAIL to test handling of tool failures

diff --git a/test/bin/dig-mock b/test/bin/dig-mock
--- a/test/bin/dig-mock
+++ b/test/bin/dig-mock
@@ -19,16 +19,26 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
-VERSION=0.1.0
+VERSION=0.2.0
 
 VERBOSE='' RREC='' HOSTS=() BRIEF='' SERVER='' HEADER=''
 
 # default name state file
 DIG_MOCK_NAMES=${DIG_MOCK_NAMES:-conf/dig-mock-names}
 
+# used to trigger failure
+DIG_MOCK_FAIL=${DIG_MOCK_FAIL-}
+
 err() { printf >&2 "%s\n" "$*"; }
 verbose() { [[ $VERBOSE ]] && err "$*"; }
-fail() { err "$*"; exit 1; }
+fail() {
+  local -i rc=1
+  printf 2>/dev/null -v rc "%d" "$1"
+  [[ $rc == 0 ]] && rc=1
+  shift
+  err "$*"
+  exit "$rc"
+}
 
 usage() {
   echo "Usage: ${0##*/} [@server] [q-type] {q-opt} host"
@@ -43,6 +53,7 @@ usage() {
   echo "       -d            (show debug messages)"
   echo "       -h            (print help and exit)"
   echo "       -v            (print version and exit)"
+  echo "       +fail[=rc]    (mock failure)"
   echo "All matches done against \"${DIG_MOCK_NAMES}\""
 }
 
@@ -98,7 +109,7 @@ match_query() { # <server> <fqdn> <ttl> <rrec> <value>
   local server=$1 fqdn=$2 rrec=$4
   local ttl=$3 val=$5
 
-  verbose "matching $@"
+  verbose "matching $*"
   [[ ${SERVER} && ${server} ]] && {
     [[ ${SERVER} == "${server}" ]] || return 1; }
   shift
@@ -117,7 +128,7 @@ do_query() { # <filename>
   local file=$1 IFS=$'\n' line found='' ttl=3600 lineno=0
   local name='' rrec='' domain='' server='' value=''
 
-  [[ -f ${file} ]] || fail "State file $file not found"
+  [[ -f ${file} ]] || fail 1 "State file $file not found"
 
   while read -r line || [[ ${line} ]]; do
     ((lineno++)) || :
@@ -129,23 +140,23 @@ do_query() { # <filename>
       # <name> <rrec> <value>
       lowercase name "$1"
       uppercase rrec "$2"
-      value=$3
+      value=${*:3}
     elif [[ ${2-} ]]; then
       case $1 in
-        \$ORIGIN) lowercase domain "$2" ;;
+        \$ORIGIN) lowercase domain "${2%.}" ;;
         \$SERVER) lowercase server "@$2" ;;
         \$TTL) ttl=$2 ;;
         *)
-          [[ ${name} ]] || fail "State file ${file}#${lineno}: missing <name>"
+          [[ ${name} ]] || fail 1 "State file ${file}#${lineno}: missing <name>"
           uppercase rrec "$1"
-          value=$2
+          value=${*:2}
           ;;
       esac
     elif [[ ${1-} ]]; then
-      fail "State file ${file}#${lineno}: invalid format"
+      fail 1 "State file ${file}#${lineno}: invalid format"
     fi
     [[ ${name} && ${rrec} && ${value} ]] && {
-      match_query "${server}" "${name}${domain:+.${domain%.}}" \
+      match_query "${server}" "${name}${domain:+.${domain}}" \
                   "${ttl}" "${rrec}" "${value}" && found=1
       value=''
     }
@@ -164,7 +175,7 @@ is_rrec() { # <arg>
 }
 
 parse_args() {
-  local arg extra='' nextarg='' warn=''
+  local arg nextarg='' warn=''
   ARGS="$*" # keep for header
   for arg in "$@"; do
     [[ ${arg} ]] || "dig: '' is not a legal name (unexpected end of input)"
@@ -175,39 +186,45 @@ parse_args() {
               else
                 err ";; Warning, ignoring invalid type $arg"; warn=1
               fi ;;
-        HOST) lowercase HOST "${arg}" ;;
+        HOST)
+          lowercase arg "${arg%.}."
+          HOSTS+=("${arg}") ;;
       esac
       nextarg=''
       continue
     }
-    case "${arg}" in
+    case ${arg} in
       -d) VERBOSE=1 ;;
       -h) usage; exit 0 ;;
       -q) nextarg=HOST ;;
       -t) nextarg=RREC ;;
       -v) err "${0##*/} ${VERSION}"; exit 0 ;;
       +short) BRIEF=1 ;;
+      +fail=*) DIG_MOCK_FAIL=${arg#+fail=} ;;
+      +fail) DIG_MOCK_FAIL=1 ;;
       +*|-*) : ;;
       @*) lowercase SERVER "${arg}" ;;
       *)
         if is_rrec "${arg}"; then
           uppercase RREC "${arg}"
         else
-          lowercase arg "${arg}"
+          lowercase arg "${arg%.}"
           HOSTS+=("${arg}")
         fi ;;
     esac
   done
-  [[ ${extra} ]] && {
-    err ";; Warning, extra type option"
-  }
   [[ ${#HOSTS[*]} != 0 || ${RREC} ]] || RREC=NS
   RREC=${RREC:-A}
   [[ ${#HOSTS[*]} != 0 ]] || HOSTS=(".")
   return 0
 }
 
+[[ ${MOCK_DEBUG} ]] && { err "${0##*/} $*"; VERBOSE=1; }
+
 parse_args "$@"
+
+[[ ${DIG_MOCK_FAIL} ]] &&
+  fail "${DIG_MOCK_FAIL}" "dig mock fail ${DIG_MOCK_FAIL}"
 
 verbose "Using state file: ${file}"
 
@@ -216,4 +233,3 @@ for HOST in "${HOSTS[@]}"; do
   verbose "looking up ${RREC} record ${HOST}"
   do_query "${DIG_MOCK_NAMES}"
 done
-
diff --git a/test/bin/nsupdate-mock b/test/bin/nsupdate-mock
--- a/test/bin/nsupdate-mock
+++ b/test/bin/nsupdate-mock
@@ -2,5 +2,29 @@
 #
 # nsupdate-mock for test scripts
 #
-[ -n "$nmg_show_debug" ] && cat -
+
+NSUPDATE_MOCK_FAIL=${NSUPDATE_MOCK_FAIL-}
+
+err() {
+  printf >&2 "%s\n" "$*"
+}
+
+fail() {
+  local -i rc=1
+  printf 2>/dev/null -v rc "%d" "$1"
+  [[ $rc == 0 ]] && rc=1
+  shift
+  err "$*"
+  exit "$rc"
+}
+
+[[ ${NSUPDATE_MOCK_FAIL} ]] &&
+  fail "${NSUPDATE_MOCK_FAIL}" "nsupdate mock fail ${NSUPDATE_MOCK_FAIL}"
+
+# echo commands if requested
+if [[ ${MOCK_ECHO} ]]; then
+  echo "nsupdate $*"
+  cat -
+fi
+
 exit 0
