general-functions v1.7.0 - added route, hash and monitor support
Added nmg_need_progs_env to better indicate which programs a missing
Added nmg:hash generic string hash function
Added nmg:ip_monitor6 to watch for changes in routes/addresses
Added several ip route functions
Added nmg::compres_ip6 - RFC5952 compressed ipv6 prefix
Added nmg::prefix_ip6 - to extract ipv6 routing prefix
Added nmg::time - supports native bash time, fallback to date cmd
Fixed a few incorrect return codes
Updated nmg::wait_dad6 to use ip_monitor6 (removed sleep)
Update nmg::{is,create}_ip6_prefix to use new ipv6 prefix code

Updated general-test:
 - added tests for new functions
 - added new tests for existing functions
 - updated verbose output for better grouping/clarity

Updated dummy-mock:
 - supports more generic usage via symlinks
 - many more config options for output redirection
 - added conditional failure support

Removed now unused pgrep-mock

Added ip-mock support files for routes and monitor

nmg_xtest now uses new shtest::clean_env to better isolate tests

diff --git a/test/bin/dummy-mock b/test/bin/dummy-mock
--- a/test/bin/dummy-mock
+++ b/test/bin/dummy-mock
@@ -1,21 +1,50 @@
 #!/bin/bash
 # -*- mode: sh; sh-basic-offset: 2; indent-tabs-mode: nil; -*-
 # vim:set ft=sh et sw=2 ts=2:
+# SPDX-License-Identifier: GPL-3.0-or-later
 #
 # General placeholder command
 #
+# Environment values:
+#
 # DUMMY_MOCK_FAIL (optional) - !0 fail code
 #
-# DUMMY_MOCK_OUTPUT (optional) - echo, "@ARGS@" replaced by arguments
+# DUMMY_MOCK_FAIL_ARGS (optional) - if args match regex, use MOCK_FAIL
+#   NOTE: each arg is enclosed in single-quotes, eg: 'first' 'second arg'
 #
-
+# DUMMY_MOCK_OUTPUT (optional) - echo value to stdout (stderr if _FAIL):
+#     "@EXE@" replaced by executable name
+#     "@ARGS@" replaced by arguments
+#
+# MOCK_ECHO (optional) - output quoted args
+#
+# MOCK_ECHO_STDIN (optional) - echos stdin
+#
+# MOCK_ECHO_STDIN_ARGS (optional) - if args match regex, use MOCK_ECHO_STDIN
+#
+# MOCK_ECHO_FD (optional) - MOCK_ECHO(_STDIN) to this file descriptor
+#
+# DUMMY_MOCK_FD (optional) - DUMMY_MOCK_OUTPUT to this file descriptor
+#
+# Any DUMMY_MOCK_<NAME>_<FILENAME> overrides above values if $0 ends
+# in <FILENAME> ('-' mapped to '_')
+#
 unset IFS
+
+set_output() {
+  [[ ${DUMMY_MOCK_FD-} ]] || return 0
+  local fd=2
+  printf 2>/dev/null -v fd "%d" "${DUMMY_MOCK_FD}" || fd=2
+  [[ $fd != 1 ]] && exec >&"$fd"
+  [[ $fd != 2 ]] && exec 2>&"$fd"
+}
 
 err() {
   printf >&2 "%s\n" "$*"
 }
 
 fail() {
+  # <rc> <output>
   local -i rc=0
   [[ $1 != 0 ]] && { printf 2>/dev/null -v rc "%d" "$1" || rc=1; }
   shift
@@ -23,10 +52,64 @@ fail() {
   exit "$rc"
 }
 
+check_overrides() {
+  local var exe=${0##*/}
+  exe=${exe//-/_}
+  var="DUMMY_MOCK_FAIL_${exe}"
+  [[ ${!var+x} ]] && DUMMY_MOCK_FAIL=${!var}
+  var="DUMMY_MOCK_FAIL_ARGS_${exe}"
+  [[ ${!var+x} ]] && DUMMY_MOCK_FAIL_ARGS=${!var}
+  var="DUMMY_MOCK_OUTPUT_${exe}"
+  [[ ${!var+x} ]] && DUMMY_MOCK_OUTPUT=${!var}
+  var="DUMMY_MOCK_FD_${exe}"
+  [[ ${!var+x} ]] && DUMMY_MOCK_FD=${!var}
+  var="MOCK_ECHO_${exe}"
+  [[ ${!var+x} ]] && MOCK_ECHO=${!var}
+  var="MOCK_ECHO_STDIN_${exe}"
+  [[ ${!var+x} ]] && MOCK_ECHO_STDIN=${!var}
+  var="MOCK_ECHO_STDIN_ARGS_${exe}"
+  [[ ${!var+x} ]] && MOCK_ECHO_STDIN_ARGS=${!var}
+  var="MOCK_ECHO_FD_${exe}"
+  [[ ${!var+x} ]] && MOCK_ECHO_FD=${!var}
+}
+
+mock_echo() {
+  # <arg>...
+  [[ ${MOCK_ECHO-} || ${MOCK_ECHO_STDIN-} ]] || return 0
+  local fd=1
+  [[ ${MOCK_ECHO_FD-} ]] && {
+    printf 2>/dev/null -v fd "%d" "${MOCK_ECHO_FD}" || fd=1
+  }
+  # echo args if requested
+  [[ ${MOCK_ECHO-} ]] && {
+    local arg out=${0##*/}
+    out=${out%-mock}
+    for arg in "$@"; do out+=" '${arg}'"; done
+    printf >&"$fd" "%s\n" "${out}"
+  }
+  # echo stdin if requested
+  [[ ${MOCK_ECHO_STDIN-} ]] && command -p cat >&"$fd" -
+}
+
+check_overrides
+
+args=''
+for arg in "$@"; do args+="${args:+ }'${arg}'"; done
+
+[[ ${DUMMY_MOCK_FAIL_ARGS-} ]] && {
+  [[ ${args} =~ ${DUMMY_MOCK_FAIL_ARGS} ]] || DUMMY_MOCK_FAIL=''
+}
+[[ ${MOCK_ECHO_STDIN_ARGS-} ]] && {
+  [[ ${args} =~ ${MOCK_ECHO_STDIN_ARGS} ]] || MOCK_ECHO_STDIN=''
+}
+
+mock_echo "$@"
+
+set_output
+
 [[ ${DUMMY_MOCK_FAIL-} || ${DUMMY_MOCK_OUTPUT-} ]] && {
-  args='' arg=''; for arg in "$@"; do args+="${args:+ }'${arg}'"; done
-  fail "${DUMMY_MOCK_FAIL:-0}" \
-       "${DUMMY_MOCK_OUTPUT+${DUMMY_MOCK_OUTPUT/@ARGS@/${args}}}"
+  out=${DUMMY_MOCK_OUTPUT+${DUMMY_MOCK_OUTPUT/@EXE@/$0}}
+  fail "${DUMMY_MOCK_FAIL:-0}" "${out/@ARGS@/$args}"
 }
 
 exit 0
diff --git a/test/conf/nmg_xtest b/test/conf/nmg_xtest
--- a/test/conf/nmg_xtest
+++ b/test/conf/nmg_xtest
@@ -19,6 +19,9 @@
 #   xwrap2 <tag> <cmd> [ <args>...]
 #     Same as xwrap, but calls shtest::prefix "<cmd>(<tag>) - " first
 #
+#   xret <tag> <ref> [ <desc> ]
+#     Same as shtest::check_result, but calls shtest::prefix " - " after
+#
 #   xrm <file> ...
 #     Removes <file>s using command -p to avoid PATH
 #
@@ -37,7 +40,13 @@
 #
 # shellcheck shell=bash disable=SC1090,SC2123
 
-# load common.conf
+TEST_CONF=${TEST_CONF-${TEST_ROOT-.}/conf}
+. "${TEST_CONF}/shtest_setup" ||
+  { echo >&2 "Unable to source shtest_setup"; exit 1; }
+
+shtest::clean_env -strict TEST*
+
+# reload common.conf
 TEST_COMMON=${TEST_COMMON:-conf/common.conf}
 { [[ -r ${TEST_COMMON} ]] && . "${TEST_COMMON}"; } ||
   { echo >&2 "Unable to load ${TEST_COMMON}"; exit 2; }
@@ -49,7 +58,6 @@ TEST_COMMON=${TEST_COMMON:-conf/common.conf}
 
 # need output directory
 [[ $TEST_OUT && -d $TEST_OUT ]] || xtest::fail "\$TEST_OUT is unset/missing!"
-[[ $TEST_OUT =~ ^/ ]] && xtest::fail "\$TEST_OUT must be relative!"
 
 NMG_XTEST_BASE=${0##*/}
 XLOG="$TEST_OUT/${NMG_XTEST_BASE}.log"
@@ -71,28 +79,33 @@ xwrap2() { # <tag> <func> [ <args>... ]
   "${_xcmd}" &>"${XERR}" 4>"${XLOG}" "$@"
 }
 
+xret() {
+  shtest::check_result "$@"
+  shtest::prefix " - "
+}
+
 xrm() {
   local f
   for f in "$@"; do [[ $f ]] && command -p rm -f "$f"; done
   return 0
 }
 
+# read stdin, strips trailing newline
 xread_value() {
-  # <retvar> <stdin
-  local IFS; unset IFS
+  # <retvar> < stdin
+  local IFS
   read -r -d '' "$1" || :
 }
 
 xread_value2() {
-  # <retvar> <stdin
-  local REPLY IFS; unset IFS
-  read -r -d '' || :
-  printf -v "$1" '%s' "${REPLY}"
+  # <retvar> < stdin
+  local IFS=-
+  read -r -d '' "$1" || :
 }
 
 xcat() {
-  # <stdin
-  local REPLY IFS; unset IFS
+  # < stdin
+  local REPLY
   read -r -d '' || printf '%s' "${REPLY}"
 }
 
@@ -111,7 +124,7 @@ xnmg::_onexit() { # <rc>
     }
     [[ -s ${XLOG} ]] && {
       shtest::alert "==== nmg log ===="
-      shtest::alert "$(< "${XLOG}" >&2)"
+      shtest::alert "$(< "${XLOG}")"
     }
   }
 
@@ -121,7 +134,7 @@ xnmg::_onexit() { # <rc>
 }
 
 xnmg::_xload_check() {
-  local xrc="exit 0" IFS; unset IFS
+  local xrc="exit 0" IFS
 
   [[ -s ${XERR}-flag ]] &&
     { read -r -d '' xrc || :; } 2>/dev/null < "${XERR}-flag"
@@ -180,12 +193,12 @@ xstart() {
   # less noise
   local -x NMG_TAG=''
 
-  # these tests require MOCK_ECHO=1 to check command actions
-  local -x MOCK_ECHO=1
-
   # fd 4 used for logger
   local -x nmg_log_stderr=4
   exec 4>&2
+
+  # redirect MOCK_ECHO to log
+  local -x MOCK_ECHO_FD=${nmg_log_stderr}
 
   (
     shtest::add_onexit xnmg::_onexit
