Updated mock executables for consistency, shellcheck fixes

diff --git a/test/bin/nmcli-mock b/test/bin/nmcli-mock
--- a/test/bin/nmcli-mock
+++ b/test/bin/nmcli-mock
@@ -19,7 +19,7 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
-VERSION=0.1.0
+VERSION=0.2.0
 
 # app in not case sensitive
 shopt -s nocasematch
@@ -37,8 +37,6 @@ shopt -s nocasematch
 # `nmcli -t -f all -m m general`
 NMCLI_MOCK_VALUES=${NMCLI_MOCK_VALUES:-conf/nmcli-mock-values}
 
-NMCLI_MOCK_FAIL=${NMCLI_MOCK_FAIL-}
-
 # only show these fields
 FIELDS=''
 # set for terse
@@ -51,20 +49,17 @@ ESCAPE=1
 ORIG_ARGS="$*"
 
 err() {
+  local IFS; unset IFS
   printf >&2 "%s\n" "$*"
 }
 
 fail() {
-  local -i rc=1
-  printf 2>/dev/null -v rc "%d" "$1"
-  [[ $rc == 0 ]] && rc=1
+  local -i rc=0
+  [[ $1 != 0 ]] && { printf 2>/dev/null -v rc "%d" "$1" || rc=1; }
   shift
-  err "$*"
+  [[ $1 ]] && { if [[ $rc == 0 ]]; then echo "$@"; else err "$@"; fi; }
   exit "$rc"
 }
-
-[[ ${NMCLI_MOCK_FAIL} ]] &&
-  fail "${NMCLI_MOCK_FAIL}" "nmcli mock fail ${NMCLI_MOCK_FAIL}"
 
 usage40() {
   printf >&2 "  %-40s %s\n" "$1" "$2"
@@ -80,6 +75,7 @@ usage() {
   usage40 "-h, --help" "print this help"
   usage40 "-m, --mode tabular|multiline" "output mode"
   usage40 "-t, --terse" "terse output"
+  usage40 "-v, --version" "show program version"
   err
   err "OBJECT"
   err "g[eneral]       NetworkManager's general status and operations"
@@ -100,7 +96,7 @@ pre_match() {
   [[ $1 ]] || return 1
   (( ${#1} > ${#2} )) && return 1
   for (( i=0; i<${#1}; i++)); do
-    [[ ${1:$i:1} == ${2:$i:1} ]] || return 1
+    [[ ${1:$i:1} == "${2:$i:1}" ]] || return 1
   done
   return 0
 }
@@ -175,6 +171,7 @@ print_values() {
       i=0
       while read -r v; do
         [[ $v || ${TERSE} ]] || v="--"
+        # shellcheck disable=SC2059
         printf "${fmt}\n" "${anames[$i]}:" "$v"
         ((i++)) || :
       done <<< "${values}"
@@ -187,6 +184,7 @@ print_values() {
         [[ ${ESCAPE} ]] && v=${v//:/\\:}
         fmt+="${fmt:+:}%s" avals+=("$v")
       done <<< "${values}"
+      # shellcheck disable=SC2059
       printf "${fmt}\n" "${avals[@]}"
     done
     return 0
@@ -209,10 +207,12 @@ print_values() {
     done
   done
   for ((j=0; j<i; j++)); do fmt+="${fmt:+  }%-${asize[$j]}s"; done
+  # shellcheck disable=SC2059
   [[ ${#anames[*]} != 0 ]] && printf "${fmt}\n" "${anames[@]}"
   for values in "$@"; do
     avals=()
     while read -r v; do avals+=("${v:---}"); done <<< "${values}"
+    # shellcheck disable=SC2059
     printf "${fmt}\n" "${avals[@]}"
   done
 }
@@ -224,11 +224,12 @@ print_section_values() {
 
   shift 2
   for entry in "${!src}"; do
+    # shellcheck disable=SC2086
     set -- ${entry}
     while [[ ${1-} ]]; do
       label=${1%%:*}
       value=${1:${#label}:${#1}}; value=${value#:}
-      if [[ ${label%%.*} != ${table} ]]; then
+      if [[ ${label%%.*} != "${table}" ]]; then
         print_values "${names}" "${values}"
         table='' names='' values=''
       fi
@@ -295,7 +296,7 @@ print_section_values() {
 print_field_values() {
   # <array-name> <fields>
   local src="$1[@]"
-  local i conn field output match label value entry items anames avals
+  local i field output match label value entry items anames avals
 
   shift
   local afields=("$@") names='' avalues=() IFS=$'\n'
@@ -303,6 +304,7 @@ print_field_values() {
   load_values "${NMCLI_MOCK_VALUES}"
 
   for entry in "${!src}"; do
+    # shellcheck disable=SC2086
     set -- ${entry}
     anames=() avals=()
     while [[ ${1-} ]]; do
@@ -498,6 +500,10 @@ do_device() {
   fail_arg "${req}"
 }
 
+[[ ${NMCLI_MOCK_FAIL-} || ${NMCLI_MOCK_OUTPUT-} ]] && {
+  unset IFS; fail "${NMCLI_MOCK_FAIL:-0}" \
+                  "${NMCLI_MOCK_OUTPUT+${NMCLI_MOCK_OUTPUT/@ARGS@/$*}}"; }
+
 while [[ ${1-} =~ ^- ]]; do
   OPTERR='' OPTARG=''
   OPT=${1#-}; OPT=${OPT#-}
@@ -518,9 +524,9 @@ while [[ ${1-} =~ ^- ]]; do
   elif pre_match "$OPT" "help"; then
     usage
   elif pre_match "$OPT" "mode"; then
-    if pre_match ${2-} "tabular"; then
+    if pre_match "${2-}" "tabular"; then
       MODE=tabular
-    elif pre_match ${2-} "multiline"; then
+    elif pre_match "${2-}" "multiline"; then
       MODE=multiline
     else
       OPTERR=$1 OPTARG=${2-}
@@ -528,6 +534,9 @@ while [[ ${1-} =~ ^- ]]; do
     shift
   elif pre_match "$OPT" "terse"; then
     TERSE=1
+  elif pre_match "$OPT" "version"; then
+    echo "nmcli-mock tool, version $VERSION"
+    exit 0
   else
     fail 2 "Error: Option '$1' is unknown, try 'nmcli -help'."
   fi
