Updated shtest, minor cleanup of ddns-funcs

diff --git a/etc/nmutils/ddns-functions b/etc/nmutils/ddns-functions
--- a/etc/nmutils/ddns-functions
+++ b/etc/nmutils/ddns-functions
@@ -1,6 +1,6 @@
 # vim:set ft=sh et sw=2 ts=2:
 #
-# NMDDNS v1.3.2 - Dynamic DNS functions scripts can include and use
+# NMDDNS v1.3.3 - Dynamic DNS functions scripts can include and use
 # Author: Scott Shambarger <devel@shambarger.net>
 #
 # Copyright (C) 2014-2021 Scott Shambarger
@@ -59,6 +59,10 @@
 #   nmddns_required_config(<config-file>) - same as
 #     nmddns_read_config but exit 0 if not found/required element missing,
 #     or exit with error if other error.
+#
+#   nmddns_config_cleanup - unset all config environment
+#
+#   nmddns_cleanup - unset all loaded environment
 #
 #   nmddns_update(<rrec> [<value> [<state-pat>]]) - set DNS resource
 #     record <rrec> to <value>, or if <value> empty, set to the
@@ -256,24 +260,37 @@ function nmddnsi_update() {
   return $rc
 }
 
+function nmddns_reset_config() {
+  local name
+  for name in "${!DDNS_RREC_@}"; do unset "$name"; done
+  unset DDNS_ZONE DDNS_SERVER DDNS_TTL DDNS_FLOCK_TIMEOUT
+  unset DDNS_DIG_TIMEOUT DDNS_DIG_RETRIES DDNS_DIG_OPTIONS
+  unset DDNS_NSUPDATE_TIMEOUT DDNS_NSUPDATE_OPTIONS DDNS_LOCKFILE
+}
+
 function nmddns_read_config() {
   # <config-file>
   local config="${1:-}"
 
+  # clear config
+  nmddns_reset_config
+
   # lockfile defaults to config-file (as it will exist if used)
   DDNS_LOCKFILE="${DDNS_GLOBAL_LOCKFILE:-$config}"
-
-  # clear config
-  DDNS_ZONE= DDNS_SERVER= DDNS_TTL= DDNS_FLOCK_TIMEOUT=
-  DDNS_DIG_TIMEOUT= DDNS_DIG_RETRIES= DDNS_DIG_OPTIONS=
-  DDNS_NSUPDATE_TIMEOUT= DDNS_NSUPDATE_OPTIONS=
-  for name in "${!DDNS_RREC_@}"; do unset "$name"; done
 
   # read config if any
   nmg_read_config "$config" || return
 
   # check required elements
   [ -n "$DDNS_ZONE" ] || return
+}
+
+function nmddns_cleanup() {
+  nmddns_reset_config
+  unset DDNS_GLOBAL_LOCKFILE DDNS_GLOBAL_FLOCK_TIMEOUT
+  unset DDNS_GLOBAL_DIG_TIMEOUT DDNS_GLOBAL_DIG_RETRIES
+  unset DDNS_GLOBAL_DIG_OPTIONS DDNS_GLOBAL_NSUPDATE_TIMEOUT
+  unset DDNS_GLOBAL_NSUPDATE_OPTIONS
 }
 
 function nmddns_required_config() {
@@ -308,7 +325,7 @@ function nmddns_update() {
     return 5
   fi
 
-  local state="${state_pat/@RREC@/$rrec}"
+  local state="${state_pat//@RREC@/$rrec}"
   if [ -n "$value" ]; then
 
     # set state if requested
@@ -349,7 +366,7 @@ function nmddns_update() {
     [ -z "$value" ] && value=$(eval echo -n '${DDNS_RREC_'$rrec'_FALLBACK:-}')
   fi
 
-  if [ -n "$DDNS_LOCKFILE" -a -n "$(command -v "$NMDDNS_FLOCK")" ]; then
+  if [ -n "${DDNS_LOCKFILE-}" -a -n "$(command -v "$NMDDNS_FLOCK")" ]; then
     local timeout="${DDNS_FLOCK_TIMEOUT:-${DDNS_GLOBAL_FLOCK_TIMEOUT:-15}}"
     ("$NMDDNS_FLOCK" -w "$timeout" 9
      [ $? -ne 0 ] && nmg_err "Timeout getting DDNS lock for $rrec" && exit 1
@@ -357,7 +374,7 @@ function nmddns_update() {
     ) 9<"$DDNS_LOCKFILE"
   else
     # no locking
-    [ -n "$DDNS_LOCKFILE" ] && nmg_info "Locking not available for DDNS"
+    [ -n "${DDNS_LOCKFILE-}" ] && nmg_info "Locking not available for DDNS"
     nmddnsi_update "$ddns_name" "$rrec" "$value"
   fi
 }
@@ -394,7 +411,7 @@ function nmddns_update_all() {
   for name in "${!DDNS_RREC_@}"; do
 
     # DDNS_RREC_<rrec>_NAME is required
-    [[ "$name" = *_NAME ]] || continue
+    [[ $name == *_NAME ]] || continue
 
     # parse rrec
     name="${name#DDNS_RREC_}"
@@ -448,7 +465,7 @@ function nmddns_spawn_update_all() {
   local name= name_found=
   for name in "${!DDNS_RREC_@}"; do
     # DDNS_RREC_<rrec>_NAME is required
-    [[ "$name" = *_NAME ]] && name_found=1 && break
+    [[ $name == *_NAME ]] && name_found=1 && break
   done
   [ -z "$name_found" ] && return
 
diff --git a/test/shtest_setup b/test/shtest_setup
--- a/test/shtest_setup
+++ b/test/shtest_setup
@@ -1,6 +1,6 @@
 # vim:set ft=sh et sw=2 ts=2:
 #
-# shtest v1.0.0 - Shell script testing functions
+# shtest v1.1.0 - Shell script testing functions
 # Author: Scott Shambarger <devel@shambarger.net>
 #
 # Copyright (C) 2021 Scott Shambarger
@@ -41,13 +41,13 @@
 #     Enables 'set -eEu' bash options, any failures a captured and fail
 #     the next shtest::check_*.  "trace" enables backtrace on failure.
 #
-#   shtest::global_whitelist <pattern>
+#   shtest::global_whitelist <pattern>...
 #
 #     Strict mode ignores failure of any function matching <pattern>
 #     Useful to allow functions in <pattern> to call functions that
 #     fail without triggering strict-mode failures.
 #
-#   shtest::whitelist <pattern>
+#   shtest::whitelist <pattern>...
 #
 #     As global_whitelist, but only until next shtest::check_* called.
 #
@@ -178,8 +178,9 @@ shtest::_init_globals() {
   # internal state
   # 0 - COUNT, 1 - FAILED, 2 - STRICT, 3 - VERBOSE, 4 - NEXT_EXITTRAP,
   # 5 - PREFIX, 6 - TRACE, 7 - LAST_CHECK, 8 - MUTE, 9 - TOP_SUBSHELL
+  # 10 - LOGFD
   _SHTEST_STATE=(0 0)
-  for (( i=2; i<=9; i++ )); do _SHTEST_STATE[${i}]=''; done
+  for (( i=2; i<=10; i++ )); do _SHTEST_STATE[${i}]=''; done
   _SHTEST_STATE[9]=${BASH_SUBSHELL}
   _SHTEST_REG_FILES=() _SHTEST_FOCUS=() _SHTEST_FAILED=()
 
@@ -205,7 +206,23 @@ shtest::_reset_state() {
 shtest::_log() { # <msg>
   # focus mutes _log too
   [[ ${_SHTEST_STATE[8]} == 1 ]] && return 0
-  printf >&88 "%s\n" "$*"
+  printf >&${_SHTEST_STATE[10]:-88} "%s\n" "$*"
+}
+
+shtest::_checkinit() {
+  [[ ${_SHTEST_STATE[0]+set} == set ]] && return
+  echo >&2 "FATAL: You must call shtest::reset after shtest::cleanup"
+  exit 1
+}
+
+shtest::log_setfd() { # <fd>/0
+  shtest::_checkinit
+  [[ ${1-} ]] || { echo -n "${_SHTEST_STATE[10]:-88}"; return 0; }
+  [[ $1 == 0 ]] && { _SHTEST_STATE[10]=''; return 0; }
+  local -i fd
+  printf 2>/dev/null -v fd "%d" "${1-}" || fd=0
+  [[ ${fd} -lt 1 ]] && shtest::fatal "shtest::set_logfd: bad fd '$1'"
+  _SHTEST_STATE[10]=${fd}
 }
 
 shtest::log() { # <msg>
@@ -222,7 +239,7 @@ shtest::_fmtlog() { # <format> <args>
   [[ ${1-} ]] || return 0
   # shellcheck disable=SC2059
   printf -v msg "$1" "${@:2}" ||
-    shtest::fatal "shtest::_fmtlog() bad format: $1" 3
+    shtest::fatal "shtest::_fmtlog: bad format: $1" 3
   shtest::log "${msg}"
 }
 
@@ -243,7 +260,7 @@ shtest::_backtrace() { # <skip>
 shtest::fatal() { # <msg> [ <backtrace-skip> ]
   # just in case...
   [[ ${_SHTEST_FATAL-} ]] &&
-    { echo >&2 "shtest::fatal(): called itself!"; exit 1; }
+    { echo >&2 "shtest::fatal: called itself!"; exit 1; }
   _SHTEST_FATAL=1
   _SHTEST_STATE[8]= # unmute
   if [[ ${1-} ]]; then
@@ -490,7 +507,7 @@ shtest::check_env() { # <id> <varname> [ <desc> ]
   local _SHTEST_NAME _SHTEST_ENV="${2}[@]" _SHTEST_NEWVARS=()
   for _SHTEST_NAME in $(compgen -v); do
     [[ ${_SHTEST_NAME} =~ ^_SHTEST_(NEWVARS|NAME|ENV)$ ]] && continue
-    [[ ${_SHTEST_NAME} =~ ^(BASH_*|LINES) ]] && continue
+    [[ ${_SHTEST_NAME} =~ ^(BASH_*|LINES|COLUMNS) ]] && continue
     [[ ${!_SHTEST_ENV} =~ (^| )"${_SHTEST_NAME}"($| ) ]] ||
       _SHTEST_NEWVARS+=("${_SHTEST_NAME}")
   done
@@ -580,23 +597,27 @@ shtest::strict() { # [ "trace" ]
   [[ ${_SHTEST_STATE[2]} ]] && return 0
   _SHTEST_STATE[2]=$(mktemp -u -t "shtest-strict-XXXXXX") || :
   [[ ${_SHTEST_STATE[2]} ]] ||
-    shtest::fatal "shtest::strict(): Unable to setup tmpfile"
+    shtest::fatal "shtest::strict: Unable to setup tmpfile"
   _SHTEST_STATE[4]=$(trap -p EXIT)
   trap 'shtest::_handle_exit $?' EXIT
   trap shtest::_handle_err ERR
   set -eEu
 }
 
-shtest::whitelist() { # <pattern>
+shtest::whitelist() { # <pattern>...
   local p
-  shtest::_toreg p "${1-}" || return
-  _SHTEST_WHITELIST+=("${p}")
+  for p in "$@"; do
+    shtest::_toreg p "${p}" || return
+    _SHTEST_WHITELIST+=("${p}")
+  done
 }
 
-shtest::global_whitelist() { # <pattern>
+shtest::global_whitelist() { # <pattern>...
   local p
-  shtest::_toreg p "${1-}" || return
-  _SHTEST_GLOBAL_WHITELIST+=("${p}")
+  for p in "$@"; do
+    shtest::_toreg p "${p}" || return
+    _SHTEST_GLOBAL_WHITELIST+=("${p}")
+  done
 }
 
 shtest::verbose() { # [ <level> ]
@@ -610,7 +631,7 @@ shtest::reset() {
   shtest::cleanup
   shtest::_init_globals
   # restore logging state
-  for i in 3 8; do _SHTEST_STATE[${i}]=${state[${i}]-}; done
+  for i in 3 8 10; do _SHTEST_STATE[${i}]=${state[${i}]-}; done
 }
 
 # initialize everything
