Cleanup of ddns-functions, added ddns-test
Renamed helper-test as general-test, moved common.sh to common.conf
Added xtest_setup, updated tests to use it. Moved *_setup to conf

diff --git a/etc/nmutils/ddns-functions b/etc/nmutils/ddns-functions
--- a/etc/nmutils/ddns-functions
+++ b/etc/nmutils/ddns-functions
@@ -1,6 +1,6 @@
 # vim:set ft=sh et sw=2 ts=2:
 #
-# NMDDNS v1.3.3 - Dynamic DNS functions scripts can include and use
+# NMDDNS v1.3.4 - Dynamic DNS functions scripts can include and use
 # Author: Scott Shambarger <devel@shambarger.net>
 #
 # Copyright (C) 2014-2021 Scott Shambarger
@@ -52,41 +52,50 @@
 #
 # Dynamic DNS functions:
 #
-#   nmddns_read_config(<config-file>) - reset config setting (including
-#     for all resource records) and read <config-file>. Return 1 if not
-#     found or required elements missing.
+#   nmddns_read_config <config-file>
 #
-#   nmddns_required_config(<config-file>) - same as
-#     nmddns_read_config but exit 0 if not found/required element missing,
-#     or exit with error if other error.
+#     Reset config setting (including for all resource records) and
+#     read <config-file>. Return 1 if not found or required elements missing.
 #
-#   nmddns_config_cleanup - unset all config environment
+#   nmddns_required_config <config-file>
 #
-#   nmddns_cleanup - unset all loaded environment
+#     Same as nmddns_read_config but exit 0 if not found/required element
+#     missing, or exit with error if other error.
 #
-#   nmddns_update(<rrec> [<value> [<state-pat>]]) - set DNS resource
-#     record <rrec> to <value>, or if <value> empty, set to the
-#     fallback value if not empty (see below), or remove the record.
-#     (DDNS_* values should be set).  If supplied, <state-pat> must
-#     contain the string "@RREC@" and is used to set state for
-#     nmddns-helper [<interface>] to update DDNS in late startup.
-#     NOTE: if <state-pat> is used, A and AAAA addresses should have /<prefix>
+#   nmddns_reset_config
 #
-#   nmddns_spawn_update(<config-file> <rrec> [<value> [state-pat>]])
-#     spawn helper to call nmddns_update asynchronously, or read
+#     Unset all config environment
+#
+#   nmddns_cleanup
+#
+#     Unset all loaded environment
+#
+#   nmddns_update <rrec> [ <value> [ <state-pat> ] ]
+#
+#     Set DNS resource record <rrec> to <value>, or if <value> empty,
+#     set to the fallback value if not empty (see below), or remove
+#     the record (DDNS_* values should be set).  If supplied,
+#     <state-pat> must contain the string "@RREC@" and is used to
+#     set state for nmddns-helper to update DDNS in late startup.
+#     NOTE: if <state-pat> is used, A and AAAA addresses should include
+#     "/<plen>" so nmddns-helper can match address is interface.
+#
+#   nmddns_spawn_update <config-file> <rrec> [ <value> [ <state-pat> ] ]
+#
+#     Spawn helper to call nmddns_update asynchronously, or read
 #     <config-file> and call it directly if helper can't be used.
 #
-#   nmddns_update_all(<"up"|"down"> <ip4-addr> <ip6-addr> [<state-pat>])
-#     updates for all configured DDNS names (DDNS_* values should be set),
-#     using <ip4-addr> for A and <ip6-addr> for AAAA (if respective
-#     DDNS_RREC_*_VALUEs don't override).  If supplied, <state-pat> must
-#     contain the string "@RREC@" and is used to set state for
-#     nmddns-helper [<interface>] to update DDNS in late startup.
-#     NOTE: if <state-pat> is used, A and AAAA addresses should have /<prefix>
+#   nmddns_update_all up | down [ <ip4-addr> <ip6-addr> [ <state-pat> ] ]
 #
-#   nmddns_spawn_update_all(<"up"|"down"> <config-file> <ip4-addr> <ip6-addr>
-#                           [<state-pat>])
-#     spawn helper to call nmddns_update_all asynchronously, or read
+#     Updates for all configured DDNS names (DDNS_* values should be set),
+#     using <ip4-addr> for A and <ip6-addr> for AAAA (if respective
+#     DDNS_RREC_*_VALUEs don't override). See nmddns_update regarding
+#     <state-pat>.
+#
+#   nmddns_spawn_update_all up | down <config-file>
+#                          [ <ip4-addr> <ip6-addr> [ <state-pat> ] ]
+#
+#     Spawn helper to call nmddns_update_all asynchronously, or read
 #     <config-file> and call it directly if helper can't be used.
 #
 # Global overrides (put in NMCONF/general.conf)
@@ -155,20 +164,21 @@
 #
 # NOTE: executable paths (see below) may be overriden if needed
 #
+# shellcheck shell=bash
 
 # set default paths if missing
 NMUTILS="${NMUTILS:-/etc/nmutils}"
-NMCONF="${NMCONF:-$NMUTILS/conf}"
+NMCONF="${NMCONF:-${NMUTILS}/conf}"
 
 ########## Global defaults (customize in $NMCONF/general.conf)
 
-DDNS_GLOBAL_LOCKFILE="${DDNS_GLOBAL_LOCKFILE:-}"
+DDNS_GLOBAL_LOCKFILE="${DDNS_GLOBAL_LOCKFILE-}"
 DDNS_GLOBAL_FLOCK_TIMEOUT="${DDNS_GLOBAL_FLOCK_TIMEOUT:-15}"
 DDNS_GLOBAL_DIG_TIMEOUT="${DDNS_GLOBAL_DIG_TIMEOUT:-3}"
 DDNS_GLOBAL_DIG_RETRIES="${DDNS_GLOBAL_DIG_RETRIES:-2}"
-DDNS_GLOBAL_DIG_OPTIONS="${DDNS_GLOBAL_DIG_OPTIONS:-}"
+DDNS_GLOBAL_DIG_OPTIONS="${DDNS_GLOBAL_DIG_OPTIONS-}"
 DDNS_GLOBAL_NSUPDATE_TIMEOUT="${DDNS_GLOBAL_NSUPDATE_TIMEOUT:-10}"
-DDNS_GLOBAL_NSUPDATE_OPTIONS="${DDNS_GLOBAL_NSUPDATE_OPTIONS:-}"
+DDNS_GLOBAL_NSUPDATE_OPTIONS="${DDNS_GLOBAL_NSUPDATE_OPTIONS-}"
 
 ########## Support programs
 
@@ -182,23 +192,23 @@ NMDDNS_FLOCK="${NMDDNS_FLOCK:-flock}"
 ########## SCRIPT START
 
 # load general-functions
-NMG="${NMG:-$NMUTILS/general-functions}"
-[ -f "$NMG" -a -r "$NMG" ] && . "$NMG" || {
-    echo 1>&2 "Unable to load $NMG" && NMG=
-  }
+NMG="${NMG:-${NMUTILS}/general-functions}"
+# shellcheck source=/dev/null
+{ [[ -r ${NMG} ]] && . "${NMG}"; } || {
+  echo 1>&2 "Unable to load ${NMG}"; NMG=''; }
 
 # private
-function nmddns_loaded() {
+function nmddns::_loaded() {
 
   # test if general-functions loaded..
-  [ -n "$NMG" ] || return
+  [[ ${NMG} ]] || return
 
   # test required programs
-  nmg_need_progs "$NMDDNS_DIG" "$NMDDNS_NSUPDATE" || return
+  nmg_need_progs "${NMDDNS_DIG}" "${NMDDNS_NSUPDATE}" || return
 }
 
 # internal
-function nmddnsi_short_timeouts() {
+function nmddns::_short_timeouts() {
   # fast timeouts with no background helper is available
   DDNS_DIG_TIMEOUT=1
   DDNS_DIG_RETRIES=0
@@ -207,62 +217,62 @@ function nmddnsi_short_timeouts() {
 }
 
 # internal
-function nmddnsi_update() {
+function nmddns::_update() {
   # <name> <rrec> <value>
-  local ddns_name="$1" ddns_rrec="$2" ddns_value="$3" cur_value=
+  local ddns_name="$1" ddns_rrec="$2" ddns_value="$3" cur_value
 
   DDNS_SERVER="${DDNS_SERVER:-127.0.0.1}"
 
   # check if server already has correct entry
-  nmg_debug "Looking up current $ddns_rrec on server $DDNS_SERVER"
+  nmg_debug "Looking up current ${ddns_rrec} on server ${DDNS_SERVER}"
 
   local qtime="${DDNS_DIG_TIMEOUT:-${DDNS_GLOBAL_DIG_TIMEOUT:-3}}"
   local qretry="${DDNS_DIG_RETRIES:-${DDNS_GLOBAL_DIG_RETRIES:-2}}"
   local qopts="${DDNS_DIG_OPTIONS:-$DDNS_GLOBAL_DIG_OPTIONS}"
-  cur_value=$("$NMDDNS_DIG" @$DDNS_SERVER +short +retry="$qretry" +time="$qtime" $qopts "$ddns_rrec" "$ddns_name")
-  [ $? -ne 0 ] && {
-    nmg_info "DNS server $DDNS_SERVER unreachable"
-    if [ -n "$ddns_value" ]; then
-      nmg_err "Update $ddns_name $ddns_rrec to $ddns_value failed"
+  # shellcheck disable=SC2086
+  if ! nmg::run cur_value "" "${NMDDNS_DIG}" "@${DDNS_SERVER}" +short +retry="${qretry}" +time="${qtime}" ${qopts} "${ddns_rrec}" "${ddns_name}"; then
+    if [[ ${ddns_value} ]]; then
+      nmg_err "Update ${ddns_name} ${ddns_rrec} to ${ddns_value} failed"
     else
-      nmg_err "Removal of $ddns_name $ddns_rrec failed"
+      nmg_err "Removal of ${ddns_name} ${ddns_rrec} failed"
     fi
     return 25
-  }
+  fi
 
-  if [ "${cur_value}" = "${ddns_value}" ]; then
-    nmg_debug "$ddns_name $ddns_rrec entry current: $cur_value"
+  if [[ ${cur_value} == "${ddns_value}" ]]; then
+    nmg_debug "${ddns_name} ${ddns_rrec} entry current: ${cur_value}"
     return
   fi
 
-  nmg_debug "Old $ddns_name $ddns_rrec value: $cur_value"
+  nmg_debug "Old ${ddns_name} ${ddns_rrec} value: ${cur_value}"
   local ddns_cmd=
-  if [ -n "$ddns_value" ]; then
-    nmg_info "Setting $ddns_name $ddns_rrec to $ddns_value"
-    ddns_cmd="update add $ddns_name ${DDNS_TTL:-600} $ddns_rrec $ddns_value"$'\n'"send"
+  if [[ ${ddns_value} ]]; then
+    nmg_info "Setting ${ddns_name} ${ddns_rrec} to ${ddns_value}"
+    ddns_cmd="update add ${ddns_name} ${DDNS_TTL:-600} ${ddns_rrec} ${ddns_value}"$'\n'"send"
   else
-    nmg_info "Removing $ddns_name $ddns_rrec"
+    nmg_info "Removing ${ddns_name} ${ddns_rrec}"
     ddns_cmd="send"
   fi
 
   # update the entry (15 sec timeout)
   local timeout="${DDNS_NSUPDATE_TIMEOUT:-${DDNS_GLOBAL_NSUPDATE_TIMEOUT:-10}}"
   local options="${DDNS_NSUPDATE_OPTIONS:-$DDNS_GLOBAL_NSUPDATE_OPTIONS}"
-  nmg_cmd "$NMDDNS_NSUPDATE" -t "$timeout" $options <<- EOF
-	server $DDNS_SERVER
-	zone $DDNS_ZONE
-	update delete $ddns_name $ddns_rrec
-	$ddns_cmd
+  # shellcheck disable=SC2086
+  nmg_cmd "${NMDDNS_NSUPDATE}" -t "${timeout}" ${options} <<- EOF
+	server ${DDNS_SERVER}
+	zone ${DDNS_ZONE}
+	update delete ${ddns_name} ${ddns_rrec}
+	${ddns_cmd}
 	EOF
   local rc=$?
-  [ $rc -ne 0 ] && nmg_err "DNS update to server $DDNS_SERVER failed for $ddns_name $ddns_rrec"
+  [[ ${rc} != 0 ]] && nmg_err "DNS update to server ${DDNS_SERVER} failed for ${ddns_name} ${ddns_rrec}"
 
-  return $rc
+  return ${rc}
 }
 
 function nmddns_reset_config() {
   local name
-  for name in "${!DDNS_RREC_@}"; do unset "$name"; done
+  for name in "${!DDNS_RREC_@}"; do unset "${name}"; done
   unset DDNS_ZONE DDNS_SERVER DDNS_TTL DDNS_FLOCK_TIMEOUT
   unset DDNS_DIG_TIMEOUT DDNS_DIG_RETRIES DDNS_DIG_OPTIONS
   unset DDNS_NSUPDATE_TIMEOUT DDNS_NSUPDATE_OPTIONS DDNS_LOCKFILE
@@ -270,19 +280,19 @@ function nmddns_reset_config() {
 
 function nmddns_read_config() {
   # <config-file>
-  local config="${1:-}"
+  local config="${1-}"
 
   # clear config
   nmddns_reset_config
 
   # lockfile defaults to config-file (as it will exist if used)
-  DDNS_LOCKFILE="${DDNS_GLOBAL_LOCKFILE:-$config}"
+  DDNS_LOCKFILE="${DDNS_GLOBAL_LOCKFILE:-${config}}"
 
   # read config if any
-  nmg_read_config "$config" || return
+  nmg_read_config "${config}" || return
 
   # check required elements
-  [ -n "$DDNS_ZONE" ] || return
+  [[ ${DDNS_ZONE} ]] || return
 }
 
 function nmddns_cleanup() {
@@ -296,107 +306,113 @@ function nmddns_cleanup() {
 function nmddns_required_config() {
   # <config-file>
   local rc=0
-  nmddns_read_config "${1:-}" || rc=$?
+  nmddns_read_config "${1-}" || rc=$?
 
   # 1 means no file, just exit 0
-  [ $rc -eq 1 ] && exit 0
+  [[ ${rc} == 1 ]] && exit 0
   # any other error, exit with it
-  [ $rc -ne 0 ] && exit $rc
+  [[ ${rc} != 0 ]] && exit ${rc}
   # no errors, continue...
   return 0
 }
 
 function nmddns_update() {
   # <rrec> [<value> [<state-pat>]]
-  local rrec="${1:-}" value="${2:-}" state_pat="${3:-}"
+  local rrec="${1-}" value="${2-}" state_pat="${3-}" name ddns_name state
+  local new_value priv_ok timeout
 
-  if [ -z "$rrec" ]; then
-    nmg_err "nmddns_update() requires <rrec> parameter"
-    return 1
-  fi
+  [[ ${rrec} ]] || {
+    nmg_err "nmddns_update: missing <rrec>"; return 1; }
 
   # are we configured to update this <rrec>?
-  local ddns_name=$(eval echo -n '${DDNS_RREC_'$rrec'_NAME:-}')
-  [ -z "$ddns_name" ] && return
+  name="DDNS_RREC_${rrec}_NAME"; ddns_name=${!name-}
+  [[ ${ddns_name} ]] || return 0
 
   # check config
-  if [ -z "${DDNS_ZONE:-}" ]; then
-    nmg_err "Missing required DDNS_ZONE config"
-    return 5
-  fi
+  [[ ${DDNS_ZONE-} ]] || {
+    nmg_err "Missing required DDNS_ZONE config"; return 5; }
 
-  local state="${state_pat//@RREC@/$rrec}"
-  if [ -n "$value" ]; then
+  [[ ${state_pat} && ${state_pat//@RREC@} == "${state_pat}" ]] && {
+    nmg_err "nmddns_update: <state-pat> must include string '@RREC@'"
+    state_pat=''
+  }
+
+  state="${state_pat//@RREC@/${rrec}}"
+  if [[ ${value} ]]; then
 
     # set state if requested
-    [ -n "$state" ] && nmg_write "$state" "$value"
+    [[ ${state} ]] && nmg_write "${state}" "${value}"
 
     # strip "/<prefix>" on A/AAAA values
-    [ "$rrec" = "A" -o "$rrec" = "AAAA" ] && value="${value%%/*}"
+    [[ ${rrec} =~ ^(A|AAAA)$ ]] && value="${value%%/*}"
 
     # use DDNS_RREC_*_VALUE, or $value if not set
-    local new_value=$(eval echo -n '${DDNS_RREC_'$rrec'_VALUE:-'$value'}')
+    name="DDNS_RREC_${rrec}_VALUE"; new_value=${!name:-${value}}
 
-    if [ "$new_value" = "$value" ]; then
+    if [[ ${new_value} == "${value}" ]]; then
 
       # SPECIAL CASE: if A or AAAA (and not changed by _VALUE), make
       # sure new value is valid
-      local priv_ok=$(eval echo -n '${DDNS_RREC_'$rrec'_PRIVATE:-}')
-      case "$rrec" in
-	"A")
-	  nmg_check_ip4_addr "$value" "$priv_ok" || new_value=
+      name="DDNS_RREC_${rrec}_PRIVATE"; priv_ok=${!name-}
+      case ${rrec} in
+	A)
+	  nmg_check_ip4_addr "${value}" "${priv_ok}" || new_value=''
 	  ;;
-	"AAAA")
-	  nmg_check_ip6_addr "$value" "$priv_ok" || new_value=
+	AAAA)
+	  nmg_check_ip6_addr "${value}" "${priv_ok}" || new_value=''
 	  ;;
       esac
     fi
 
     # use fallback (if any) if <new_value> empty
-    [ -z "$new_value" ] && new_value=$(eval echo -n '${DDNS_RREC_'$rrec'_FALLBACK:-}')
+    [[ ${new_value} ]] || {
+      name="DDNS_RREC_${rrec}_FALLBACK"; new_value=${!name-}; }
 
     # new_value of * means remove entry on set (ignoring fallback)
-    [ "$new_value" = "*" ] && value= || value="$new_value"
+    [[ ${new_value} == "*" ]] && value='' || value=${new_value}
   else
 
     # remove state if requested
-    [ -n "$state" ] && nmg_remove "$state"
+    [[ ${state} ]] && nmg_remove "${state}"
 
     # clearing value, use fallback (if any)
-    [ -z "$value" ] && value=$(eval echo -n '${DDNS_RREC_'$rrec'_FALLBACK:-}')
+    [[ ${value} ]] || {
+      name="DDNS_RREC_${rrec}_FALLBACK"; value=${!name-}; }
   fi
 
-  if [ -n "${DDNS_LOCKFILE-}" -a -n "$(command -v "$NMDDNS_FLOCK")" ]; then
-    local timeout="${DDNS_FLOCK_TIMEOUT:-${DDNS_GLOBAL_FLOCK_TIMEOUT:-15}}"
-    ("$NMDDNS_FLOCK" -w "$timeout" 9
-     [ $? -ne 0 ] && nmg_err "Timeout getting DDNS lock for $rrec" && exit 1
-     nmddnsi_update "$ddns_name" "$rrec" "$value"
-    ) 9<"$DDNS_LOCKFILE"
+  if [[ ${DDNS_LOCKFILE-} ]] && command &>/dev/null -v "${NMDDNS_FLOCK}"; then
+    timeout="${DDNS_FLOCK_TIMEOUT:-${DDNS_GLOBAL_FLOCK_TIMEOUT:-15}}"
+    ("${NMDDNS_FLOCK}" -w "${timeout}" 9 || {
+       nmg_err "Timeout getting DDNS lock for ${rrec}"; exit 1; }
+     nmddns::_update "${ddns_name}" "${rrec}" "${value}"
+    ) 9<"${DDNS_LOCKFILE}" || return
   else
     # no locking
-    [ -n "${DDNS_LOCKFILE-}" ] && nmg_info "Locking not available for DDNS"
-    nmddnsi_update "$ddns_name" "$rrec" "$value"
+    [[ ${DDNS_LOCKFILE-} ]] && nmg_info "Locking not available for DDNS"
+    nmddns::_update "${ddns_name}" "${rrec}" "${value}" || return
   fi
+  return 0
 }
 
 function nmddns_spawn_update() {
   # <ddns-file> <rrec> [<value> [<state-pat>]]
-  local config="${1:-}" rrec="${2:-}" state_pat="${4:-}"
+  local config="${1-}" rrec="${2-}" name ddns_name
 
-  [ -z "$rrec" ] && return
+  [[ ${rrec} ]] || return 0
 
   # check if config exists
-  nmddns_read_config "$config" || return 0
+  nmddns_read_config "${config}" || return 0
 
   # check if name configured
-  local ddns_name=$(eval echo -n '${DDNS_RREC_'$rrec'_NAME:-}')
-  [ -z "$ddns_name" ] && return
+  name="DDNS_RREC_${rrec}_NAME"; ddns_name=${!name-}
+  [[ ${ddns_name} ]] || return 0
 
   # we have a valid config, spawn the helper
-  nmg_daemon "$NMDDNS_HELPER" "update" "$@" && return
+  [[ ${NMDDNS_HELPER-} ]] &&
+    nmg_daemon "${NMDDNS_HELPER}" "update" "$@" && return
 
   # make timeouts much faster, or NetworkManager will kill us
-  nmddnsi_short_timeout
+  nmddns::_short_timeouts
 
   # helper not found, or can't be started, update directly.
   shift 1
@@ -404,84 +420,85 @@ function nmddns_spawn_update() {
 }
 
 function nmddns_update_all() {
-  # <"up"|"down"> <ip4-addr> <ip6-addr> [<state-pat>]
-  local action="$1" addr4="${2:-}" addr6="${3:-}" state_pat="${4:-}"
+  # <"up"|"down"> [ <ip4-addr> <ip6-addr> [ <state-pat> ] ]
+  local action="$1" addr4="${2-}" addr6="${3-}" state_pat="${4-}"
+  local name rrec value
 
-  local name=
   for name in "${!DDNS_RREC_@}"; do
 
     # DDNS_RREC_<rrec>_NAME is required
-    [[ $name == *_NAME ]] || continue
+    [[ ${name} =~ _NAME$ ]] || continue
 
     # parse rrec
-    name="${name#DDNS_RREC_}"
-    local rrec="${name%_NAME}"
-    [ -z "$rrec" ] && continue
+    name=${name#DDNS_RREC_}
+    rrec=${name%_NAME}
+    [[ ${rrec} ]] || continue
 
-    case "$action" in
-      "up")
+    case ${action} in
+      up)
 	# special case values for A and AAAA
-	case "$rrec" in
-	  "A")
-	    value="$addr4"
+	case ${rrec} in
+	  A)
+	    value="${addr4}"
 	    ;;
-	  "AAAA")
-	    value="$addr6"
+	  AAAA)
+	    value="${addr6}"
 	    ;;
 	  *)
-	    value="$(eval echo -n '${DDNS_RREC_'$rrec'_VALUE:-}')"
+            name="DDNS_RREC_${rrec}_VALUE"; value=${!name-}
 	    ;;
 	esac
 	;;
-      "down")
-	value=
+      down)
+	value=''
 	;;
       *)
-	nmg_err "nmddns_update_all() requires an <action> of 'up' or 'down'"
+	nmg_err "nmddns_update_all: <action> must be 'up' or 'down'"
 	return 1
 	;;
     esac
 
     # perform update
-    nmddns_update "$rrec" "$value" "$state_pat"
+    nmddns_update "${rrec}" "${value}" "${state_pat}"
   done
 
   return 0
 }
 
 function nmddns_spawn_update_all() {
-  # <"up"|"down"> <config-file> <ip4-addr> <ip6-addr> <state-pat>
-  local action="${1:-}" config="${2:-}" addr4="${3:-}" addr6="${4:-}" state_pat="${5:-}"
+  # <"up"|"down"> <config-file> [ <ip4-addr> <ip6-addr> [ <state-pat> ] ]
+  local action="${1-}" config="${2-}"
 
-  [ -z "$action" ] && {
-    nmg_err "nmddns_spawn_update_all() requires an <action> of 'up' of 'down'"
+  [[ ${action} =~ ^up|down$ ]] || {
+    nmg_err "nmddns_spawn_update_all: <action> must be 'up' of 'down'"
     return 1
   }
 
   # check if config exists
-  nmddns_read_config "$config" || return 0
+  nmddns_read_config "${config}" || return 0
 
   # check if any names configured
-  local name= name_found=
+  local name name_found=''
   for name in "${!DDNS_RREC_@}"; do
     # DDNS_RREC_<rrec>_NAME is required
-    [[ $name == *_NAME ]] && name_found=1 && break
+    [[ ${name} =~ _NAME$ ]] && name_found=1 && break
   done
-  [ -z "$name_found" ] && return
+  [[ ${name_found} ]] || return 0
 
   # we have a valid config, spawn the helper
-  nmg_daemon "$NMDDNS_HELPER" "$@" && return
+  nmg_daemon "${NMDDNS_HELPER}" "$@" && return
 
   # make timeouts much faster, or NetworkManager will kill us
-  nmddnsi_short_timeout
+  nmddns::_short_timeout
 
   # helper not found, or can't be started, update directly.
   shift 2
-  nmddns_update_all "$action" "$@"
+  nmddns_update_all "${action}" "$@"
 }
 
 # last, to fail load if any missing components
-nmddns_loaded
+nmddns::_loaded
+
 # Local Variables:
 # mode: sh
 # sh-basic-offset: 2
diff --git a/test/general-test b/test/general-test
--- a/test/general-test
+++ b/test/general-test
@@ -1,64 +1,31 @@
 #!/bin/bash
+# vim:set ft=sh et sw=2 ts=2:
 #
-# Test suite for general-functions and ddns-functions
+# Test suite for general-functions
 #
 
-# if desired, export nmg_show_debug as we use in some test programs
-#export nmg_show_debug=1
-
-xtest::err() {
-  echo >&2 "$*"
-}
-
-xtest::fail() {
-  xtest::err "$*"
-  exit 1
-}
-
-# load common.sh
-TEST_COMMON=${TEST_COMMON:-conf/common.sh}
+# load common.conf
+TEST_COMMON=${TEST_COMMON:-conf/common.conf}
 # shellcheck source=/dev/null
 { [[ -r ${TEST_COMMON} ]] && . "${TEST_COMMON}"; } ||
-  xtest::fail "Unable to load common.sh"
+  { echo >&2 "Unable to load ${TEST_COMMON}"; exit 2; }
 
 # shellcheck source=/dev/null
-. "${TEST_ROOT-.}/shtest_setup" ||
-  xtest::fail "Unable to source shtest_setup"
+[[ ${XTEST_SETUP} ]] && . "${XTEST_SETUP}"
+
+NMG="${NMG:-${NMUTILS}/general-functions}"
 
 # ensure includes pass parse test
-shtest::parse "${NMUTILS}/general-functions" || shtest::fatal
-shtest::parse "${NMUTILS}/ddns-functions" || shtest::fatal
+shtest::parse "${NMG}" || shtest::fatal
 
-# normal startup
-
-# load ddns- or general-functions
-NMDDNS="${NMDDNS:-${NMUTILS}/ddns-functions}"
 # shellcheck source=/dev/null
-{ [[ -r ${NMDDNS} ]] && . "${NMDDNS}"; } || {
-  # no DDNS, use general-functions
-  NMDDNS='' NMG="${NMG:-${NMUTILS}/general-functions}"
-  # shellcheck source=/dev/null
-  { [[ -r ${NMG} ]] && . "${NMG}"; } || {
-    echo 1>&2 "Unable to read ${NMG}" && exit 2; }
-}
+. "${NMG}"
 
-xtest::reg_test() { # <id> <ref> <desc>
-  # LOG matches <ref>, ERR should be empty...
-  shtest::check_reg_files "${1-}" "${3-}" "${2-}"
-}
+# less noise
+export NMG_TAG=''
 
-xtest::reg_test2() { # <id> <ref> <stderr/out> <desc>
-  # LOG matches <ref>, ERR matches <err>
-  shtest::check_reg_files "${1-}" "${4-}" "${2-}" "${3-}"
-}
-
-# make tests easier to add
-shopt -s expand_aliases
-alias xtest='shtest::check_result'
-alias vtest='shtest::check_var'
-alias atest='shtest::check_array'
-alias ftest='xtest::reg_test'
-alias ftest2='xtest::reg_test2'
+# these tests require MOCK_ECHO=1 to check command actions
+export MOCK_ECHO=1
 
 xwrap() {
   local cmd=${1-}
@@ -70,7 +37,6 @@ xwrap() {
 xtest::group1::log() {
   local nmg_show_debug=''
 
-  # shellcheck disable=SC2034
   local NMG_LOGGER=echo
 
   shtest::title "nmg_log() tests"
@@ -146,6 +112,8 @@ xtest::group1::log() {
   nmg_log >"${XERR}" 2>&- err "stderr closed"
   xtest L12 t "(err <stderr closed>) returns true"
   ftest L12f "" " - should not generate output"
+
+  : "${NMG_LOGGER-}" # for SC
 }
 
 xtest::group2::err() {
@@ -252,7 +220,6 @@ xtest::group3::cmd() {
   vtest X3v "" " - should clear retvar"
   ftest X3f "ERR: FAIL(5) DRY-RUN: true" " - should log err"
 
-  # shellcheck disable=SC2034
   nmg_dryrun=0 nmg_show_debug=1
   xwrap nmg::run var err "$XFILE" 0
   xtest X4 t "(<dry-run>) returns true"
@@ -305,7 +272,6 @@ xtest::group3::cmd() {
   shtest::prefix "nmg_daemon"
 
   # make sure we don't use cgroups in tests
-  # shellcheck disable=SC2034
   local NMG_DAEMON_CGROUP=
 
   xwrap nmg_daemon
@@ -323,28 +289,8 @@ xtest::group3::cmd() {
   xwrap nmg_daemon "$XNOFILE"
   xtest X43 f "('not-there') returns false"
   ftest X43f "ERR: nmg_daemon: command '$XNOFILE' not found" " - logs error"
-}
 
-xtest::group3::ddns() {
-  # check if ddns funcs avail
-  [ -z "$NMDDNS" ] && return
-
-  local cnf="$NMCONF/ddns-test.conf"
-
-  shtest::title "nmddns tests"
-
-  shtest::prefix "nmddns_spawn_update"
-
-  nmddns_spawn_update "$cnf"
-  xtest D1 t "($cnf) returns true"
-  nmddns_spawn_update "$cnf" AAAA fddd:dead:beef::1
-  xtest D2 t "(AAAA <ip>) returns true"
-  nmddns_spawn_update "$cnf" A;
-  xtest D3 t "(A <empty) returns true"
-  nmddns_spawn_update "$cnf" A 1.2.3.4
-  xtest D4 t "(A <ip) returns true"
-
-  nmddns_cleanup
+  : "${nmg_dryrun-} ${nmg_show_debug-} ${NMG_DAEMON_CGROUP-}" # for SC
 }
 
 xtest::group3::ip() {
@@ -356,7 +302,7 @@ xtest::group3::ip() {
 
   xwrap nmg::query_ips avar "" 4 "eth0" "^192.*"
   xtest I1 t "(4 eth0 192.*) returns true"
-  aref=("192.168.10.4/24 8600sec 2400sec")
+  aref=("192.168.66.4/24 8600sec 2400sec")
   atest I1a avar aref " - returns address and lifetimes"
   ftest I1f "" " - should not log"
 
@@ -434,13 +380,13 @@ xtest::group3::ip4() {
 
   shtest::prefix "nmg_check_ip4_addr"
 
-  nmg_check_ip4_addr 192.168.1.1
-  xtest V1 3 "('192.168.1.1') returns 3"
-  nmg_check_ip4_addr 192.168.1.1 1
-  xtest V2 t "('192.168.1.1' 1) <private>, returns true"
+  nmg_check_ip4_addr 192.168.88.1
+  xtest V1 3 "('192.168.88.1') returns 3"
+  nmg_check_ip4_addr 192.168.88.1 1
+  xtest V2 t "('192.168.88.1' 1) <private>, returns true"
   nmg_check_ip4_addr 172.16.1.1
   xtest v3 3 "('172.16.1.1'), returns 3"
-  nmg_check_ip4_addr 8.8.8.8
+  nmg_check_ip4_addr 203.0.113.8
   xtest v4 t "(<dns>), returns true"
   nmg_check_ip4_addr 127.0.0.1
   xtest v5 2 "('127.0.0.1'), returns 2"
@@ -460,7 +406,7 @@ xtest::group3::ip4() {
 
   xwrap nmg_find_ip4_addrs "eth0"
   xtest V13 t "(eth0) returns true"
-  ftest2 V13f "" "192.168.10.4/24" " - returns matching address"
+  ftest2 V13f "" "192.168.66.4/24" " - returns matching address"
 
   shtest::prefix "nmg_add_ip4_addr"
 
@@ -587,7 +533,6 @@ xtest::group3::file() {
   xtest F2 5 "(<dry-run 5>) returns 5"
   ftest F2f "ERR: FAIL(5): DRY-RUN: nmg_write($XFILE)" " - logs error"
 
-  # shellcheck disable=SC2034
   nmg_dryrun=0
   xwrap nmg_write "$XFILE" "content"
   xtest F3 t "(<dry-run>) returns true"
@@ -678,6 +623,8 @@ xtest::group3::file() {
   ftest F32f "" " - should not log"
   [[ -f "$XFILE" ]]
   xtest F32r f " - file should be removed"
+
+  : "${nmg_dryrun-}" # for SC
 }
 
 xtest::group3::misc() {
@@ -735,9 +682,6 @@ xtest::group3::misc() {
 xtest::group4::config() {
   local var=''
 
-  # shellcheck disable=SC2034
-  local cfg_env; shtest::save_env cfg_env
-
   shtest::title "Config function tests"
 
   shtest::prefix "nmg_read_config"
@@ -777,7 +721,6 @@ xtest::group4::config() {
   xtest C7 t "(<file w/ output>) returns true"
   ftest C7f "" " - should not output/log"
 
-  # shellcheck disable=SC2034
   unset var
   echo "var='new value'" > "$XFILE"
   xwrap nmg_read_config "$XFILE"
@@ -805,73 +748,11 @@ xtest::group4::config() {
   vtest C23 2 "(<bad file>) exits 2"
   ftest C23f "ERR: Failed to parse config file '$XFILE': ${XFILE}: line 3: syntax error: unexpected end of file" \
         " - logs error"
+
+  : "${var-}" # for SC
 }
 
-xtest::usage() { # <modes>
-  local mode modes=()
-  xtest::err "Usage: ${0##*/} <options>"
-  xtest::err "  <options> include:"
-  xtest::err "    help - show help"
-  xtest::err "    verbose - always show test descriptions"
-  xtest::err "    quiet - show summary only"
-  xtest::err "    strict - enable -eEu bash option"
-  xtest::err "    trace - enable -eEu bash option with traceback"
-  xtest::err "    all - run all tests (default)"
-  xtest::err "    +<id/pattern> - show test <id/pattern(*|?)> (may be repeated)"
-  for mode in "$@"; do modes+=("${mode#xtest::group*::}"); done
-  xtest::err "    ${modes[*]} - include these groups"
-  shtest::cleanup
-  exit 1
-}
-
-xtest::perform_tests() { # <args>...
-  local arg all reqs=()
-
-  { read -r -a all -d '' || :; } \
-    <<< "$(compgen -A function xtest::group | sort)"
-
-  for arg in "$@"; do
-    if [[ "${all[*]}" =~ (^| )(xtest::group.::"$arg")($| ) ]]; then
-      reqs+=("${BASH_REMATCH[2]}")
-    else
-      case $arg in
-        all) : ;;
-        strict|trace)
-          shtest::strict "${arg[@]/strict/}"
-          shtest::global_whitelist "xtest::group*" "xwrap"
-          ;;
-        verbose)
-          shtest::verbose
-          ;;
-        quiet)
-          shtest::quiet
-          ;;
-        +*)
-          arg=${arg#+}; [[ $arg ]] || xtest::usage "${all[@]}"
-          shtest::add_focus "${arg}"
-          ;;
-        help)
-          xtest::usage "${all[@]}"
-          ;;
-        *)
-          xtest::err "Unknown option: ${arg}"
-          xtest::usage "${all[@]}"
-          ;;
-      esac
-    fi
-  done
-
-  local func_env
-  for arg in "${reqs[@]:-${all[@]}}"; do
-    shtest::save_env func_env
-    "$arg"
-    shtest::prefix
-    shtest::check_env "ENV-${arg##*:}" func_env "check config environment"
-  done
-  : "${func_env-}" # for SC
-}
-
-xtest::run_tests() {
+main() {
 
   [[ $EUID == 0 ]] && shtest::fatal "Never run as root!"
 
@@ -881,8 +762,7 @@ xtest::run_tests() {
   local XNOFILE="$TEST_OUT/no-file" XFILE="$TEST_OUT/xtest file"
   local XLOG="$TEST_OUT/xtest log" XERR="$TEST_OUT/xtest err"
 
-  # shellcheck disable=SC2034
-  local nmg_log_stderr=4 xtest_env; shtest::save_env xtest_env
+  export nmg_log_stderr=4
 
   # fd 4 used for logger
   exec 4>&2
@@ -890,7 +770,7 @@ xtest::run_tests() {
   shtest::reg_file "$XLOG"
   shtest::reg_file "$XERR"
 
-  xtest::perform_tests "$@"
+  xtest::run_tests "general-functions Test Summary" "$@"
 
   # cleanup
   [[ -f $XFILE ]] && rm -f "$XFILE"
@@ -898,14 +778,14 @@ xtest::run_tests() {
   [[ -f $XERR ]] && rm -f "$XERR"
   exec 4>&-
 
-  shtest::title "Final tests"
-  shtest::check_env ENV-all xtest_env "check environment"
-  shtest::summary_report || {
-    shtest::log "To display one test, use \"+<id/pattern>\" (repeatable)"
-  }
+  return 0
 }
 
-# shellcheck disable=SC2034
-NMG_TAG=''
-xtest::run_tests "$@"
-shtest::cleanup
+main "$@"
+
+# Local Variables:
+# mode: sh
+# sh-basic-offset: 2
+# sh-indentation: 2
+# indent-tabs-mode: nil
+# End:
