Cleanup of nmddns-helper, add helper tests

diff --git a/sbin/nmddns-helper b/sbin/nmddns-helper
--- a/sbin/nmddns-helper
+++ b/sbin/nmddns-helper
@@ -1,10 +1,10 @@
 #!/bin/bash
 # vim:set ft=sh et sw=2 ts=2:
 #
-# nmddns-helper v1.1.0 - NMUtils Dynamic DNS helper program
+# nmddns-helper v1.1.1 - NMUtils Dynamic DNS helper program
 # Author: Scott Shambarger <devel@shambarger.net>
 #
-# Copyright (C) 2014-2019 Scott Shambarger
+# Copyright (C) 2014-2021 Scott Shambarger
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -42,7 +42,7 @@
 #
 
 # for logging
-NMG_TAG="${NMG_TAG:-nmddns}"
+NMG_TAG="${NMG_TAG-nmddns}"
 
 # set NMUTILS/NMCONF early, and allow environment to override
 NMUTILS="${NMUTILS:-/etc/nmutils}"
@@ -57,123 +57,127 @@ RUNDIR="${RUNDIR:-/run/nmutils}"
 ########## SCRIPT START
 
 # load ddns-functions
-NMDDNS="${NMDDNS:-$NMUTILS/ddns-functions}"
-[ -f "$NMDDNS" -a -r "$NMDDNS" ] && . "$NMDDNS" || {
-    echo 1>&2 "Unable to load $NMDDNS" && exit 2
-  }
+NMDDNS="${NMDDNS:-${NMUTILS}/ddns-functions}"
+# shellcheck disable=SC1090
+{ [[ -r ${NMDDNS} ]] && . "${NMDDNS}"; } || {
+  echo 1>&2 "Unable to load ${NMDDNS}"; exit 2; }
 
 ########## Config locations
 
-# NOTE: *_PAT variables must have @MATCH@ and @RREC@ keywords
+# NOTE: *_PAT variables must have a single @MATCH@ and @RREC@ keyword
 NMDDNS_CONFIG_PAT="${NMDDNS_CONFIG_PAT:-$NMCONF/ddns-@MATCH@.conf}"
 NMDDNS_STATE_PAT="${NMDDNS_STATE_PAT:-$RUNDIR/ddns-@MATCH@-@RREC@.state}"
 
 function ddns_update() {
   # <rrec> [<value>]
-  local rrec="$1" value="${2:-}" rc=0
+  local rrec="${1-}" value="${2-}" rc=0
 
-  [ -n "$rrec" ] || return 0
+  [[ ${rrec} ]] || return 0
 
-  nmddns_update "$rrec" "$value" || rc=$?
+  nmddns_update "${rrec}" "${value}" || rc=$?
 
   # allow server unreachable...
-  [ $rc -eq 25 ] && return 0
+  [[ ${rc} == 25 ]] && return 0
 
-  return $rc
+  return ${rc}
 }
 
 function ddns_interface_rrec() {
   # <interface> <state-pat> <rrec>
   local intf="$1" state_pat="$2" rrec="$3"
 
-  local state="${state_pat/@RREC@/$rrec}"
+  local state="${state_pat//@RREC@/${rrec}}"
 
-  local value=
-  [ -f "$state" -a -r "$state" ] && value=$(< "$state")
+  nmg::read value ignore "${state}"
+  # first line only...
+  value=${value%%$'\n'*}
 
-  if [ -n "$value" ]; then
+  if [[ ${value} ]]; then
     # ensure if address, it can be found on the interface
-    case "$rrec" in
-      "A")
-	value=$(nmg_find_ip4_addrs "$intf" "$value")
-	;;
-      "AAAA")
-	value=$(nmg_find_ip6_addrs "$intf" "$value")
-	;;
+    case ${rrec} in
+      A)
+        nmg_debug "Checking if ${intf} has ip4 ${value}"
+        value=$(nmg_find_ip4_addrs "${intf}" "${value}") ;;
+      AAAA)
+        nmg_debug "Checking if ${intf} has ip6 ${value}"
+        value=$(nmg_find_ip6_addrs "${intf}" "${value}") ;;
     esac
   fi
 
-  ddns_update "$rrec" "$value"
+  ddns_update "${rrec}" "${value}"
 }
 
 function ddns_interface() {
-  # [<interface>]
-  local interface="${1:-}" rc=0
+  # [ <interface> ]
+  local interface=${1-} rc=0
 
   local config_pre="${NMDDNS_CONFIG_PAT%@MATCH@*}"
   local config_post="${NMDDNS_CONFIG_PAT##*@MATCH@}"
 
-  shopt -s nullglob
-  local config=
-  for config in "$config_pre"*"$config_post"; do
+  local config intf
+  for config in "${config_pre}"*"${config_post}"; do
+
+    # config has * if no matches...
+    [[ ${config} == "${NMDDNS_CONFIG_PAT/@MATCH@/*}" ]] && break
 
     # get match part
-    local match="${config#$config_pre}"
-    match="${match%$config_post}"
-    [ -z "$match" ] && continue
+    local match="${config#${config_pre}}"
+    match="${match%${config_post}}"
+    [[ ${match} ]] || continue
 
     # find interface (remove any -prefix etc)
-    local intf="${match%%-*}"
+    intf="${match%%-*}"
 
     # if we have an interface, make sure we filter for it
-    [ -z "$interface" -o "$intf" = "$interface" ] || continue
+    [[ ${interface} && ${interface} != "${intf}" ]] && continue
 
     # load DDNS config
-    nmddns_read_config "$config" || continue
+    nmddns_read_config "${config}" || continue
 
     # get state file pattern
-    local state_pat="${NMDDNS_STATE_PAT/@MATCH@/$match}"
+    local state_pat="${NMDDNS_STATE_PAT/@MATCH@/${match}}"
 
-    local name=
+    local name rrec
     for name in "${!DDNS_RREC_@}"; do
-      name="${name#DDNS_RREC_}"
-      [[ "$name" = *_NAME ]] || continue
-      ddns_interface_rrec "$intf" "$state_pat" "${name%_NAME}" || rc=$?
+      [[ ${name} =~ _NAME$ ]] || continue
+      name=${name#DDNS_RREC_}
+      rrec=${name%_NAME}
+      [[ ${rrec} ]] || continue
+      ddns_interface_rrec "${intf}" "${state_pat}" "${rrec}" || rc=$?
     done
   done
 
-  return $rc
+  return ${rc}
 }
 
 function ddns_helper_action() {
-  # <action> <config-file> <args>...
-  local action="${1:-}" config="${2:-}"; shift 2
+  # <action> <config-file> [ <args>... ]
+  local action=$1 config=$2; shift 2
 
-  case "$action" in
-    "update")
-      nmddns_required_config "$config"
+  case ${action} in
+    update)
+      nmddns_required_config "${config}"
       nmddns_update "$@"
       ;;
-    "up"|"down")
-      nmddns_required_config "$config"
-      nmddns_update_all "$action" "$@"
+    up|down)
+      nmddns_required_config "${config}"
+      nmddns_update_all "${action}" "$@"
       ;;
     *)
-      echo 1>&2 "Usage: ${0##*/} [<interface>]"
+      echo 1>&2 "Usage: ${0##*/} [ <interface> ]"
       return 1
       ;;
   esac
 }
 
-[ -e "$RUNDIR" ] || {
-  nmg_cmd mkdir -p "$RUNDIR" || exit
-}
+[[ -e ${RUNDIR} ]] || { nmg_cmd mkdir -p "${RUNDIR}" || exit; }
 
-if [ -z "${2:-}" ]; then
-  ddns_interface "${1:-}"
-else
+if [[ ${2-} ]]; then
   ddns_helper_action "$@"
+else
+  ddns_interface "$@"
 fi
+
 # Local Variables:
 # mode: sh
 # sh-basic-offset: 2
diff --git a/test/conf/shtest_setup b/test/conf/shtest_setup
--- a/test/conf/shtest_setup
+++ b/test/conf/shtest_setup
@@ -1,6 +1,6 @@
 # vim:set ft=sh et sw=2 ts=2:
 #
-# shtest v1.1.1 - Shell script testing functions
+# shtest v1.2.0 - Shell script testing functions
 # Author: Scott Shambarger <devel@shambarger.net>
 #
 # Copyright (C) 2021 Scott Shambarger
@@ -114,10 +114,10 @@
 #
 #     Remove <filename> from shtest::check_reg_files tests.
 #
-#   shtest::check_reg_files <id> <desc> [ <fileX_contents>... ]
+#   shtest::check_reg_files <id> <desc> [ <file#-contents>... ]
 #
 #     Checks contents of files registered with shtest::reg_file
-#     in order against <fileX_contents>, displays "<id> OK" or
+#     in order against <file#-contents>, displays "<id> OK" or
 #     <id> FAIL | <desc>" including expected vs actual for first
 #     file with mis-matched content.
 #
@@ -179,9 +179,9 @@ shtest::_init_globals() {
   # internal state
   # 0 - COUNT, 1 - FAILED, 2 - STRICT, 3 - VERBOSE, 4 - NEXT_EXITTRAP,
   # 5 - PREFIX, 6 - TRACE, 7 - LAST_CHECK, 8 - MUTE, 9 - TOP_SUBSHELL
-  # 10 - LOGFD
+  # 10 - LOGFD, 11 - MULTI_TEST
   _SHTEST_STATE=(0 0)
-  for (( i=2; i<=10; i++ )); do _SHTEST_STATE[${i}]=''; done
+  for (( i=2; i<=11; i++ )); do _SHTEST_STATE[${i}]=''; done
   _SHTEST_STATE[9]=${BASH_SUBSHELL}
   _SHTEST_REG_FILES=() _SHTEST_FOCUS=() _SHTEST_FAILED=()
 
@@ -295,8 +295,10 @@ shtest::_log_fail() { # <id> <description> [ <reason> | <expect> <found> ]
     shtest::log "        reason: ${3-}"
   fi
   ((_SHTEST_STATE[1]++)) || :
-  _SHTEST_FAILED+=("${id}")
-  [[ ${#_SHTEST_FOCUS[*]} != 0 ]] && _SHTEST_STATE[8]=1
+  [[ ${_SHTEST_STATE[11]} ]] || {
+    _SHTEST_FAILED+=("${id}")
+    [[ ${#_SHTEST_FOCUS[*]} != 0 ]] && _SHTEST_STATE[8]=1
+  }
   return 0
 }
 
@@ -461,18 +463,28 @@ shtest::dereg_file() { # <filename>
   done
 }
 
-shtest::check_reg_files() { # <id> <desc> [ <fileX_contents>... ]
-  local id=${1-} desc=${2-} file rc
+shtest::check_reg_files() { # <id> <desc> [ <file#-contents>... ]
+  local id=${1-} desc=${2-} file rc fails num
   [[ ${id} ]] ||
-    shtest::fatal "Usage: shtest::check_reg_files <id> <desc> [ <fileX_contents>... ]" 3
+    shtest::fatal "Usage: shtest::check_reg_files <id> <desc> [ <file#-contents>... ]" 3
   shtest::_check_entry "${id}" "${desc}" || return 0
   shift 2 || set --
+  fails=${_SHTEST_STATE[1]} num=0
+  _SHTEST_STATE[11]=1 # multi-test state
   for file in "${_SHTEST_REG_FILES[@]-}"; do
-    [[ ${file} ]] || break
-    shtest::_check_file "${id}" "${file}" "${1-}" "${desc}"
-    [[ ${rc} != 0 ]] && return 0
+    ((num++)) || :
+    [[ ${file} ]] || continue
+    shtest::_check_file "${id}" "${file}" "${1-}" "${desc} (reg ${num})"
     shift || set --
   done
+  _SHTEST_STATE[11]='' # reset multi-test
+  [[ ${fails} != ${_SHTEST_STATE[1]} ]] && {
+    # multiple file failures is only a single test failure
+    _SHTEST_STATE[1]=$((++fails))
+    _SHTEST_FAILED+=("${id}")
+    [[ ${#_SHTEST_FOCUS[*]} != 0 ]] && _SHTEST_STATE[8]=1
+    return 0
+  }
   shtest::_log_ok "${id}" "${desc}"
 }
 
