08-ipv6-prefix v1.99.7 - add DAD check on LAN, cleanup logging

diff --git a/etc/NetworkManager/dispatcher.d/08-ipv6-prefix b/etc/NetworkManager/dispatcher.d/08-ipv6-prefix
--- a/etc/NetworkManager/dispatcher.d/08-ipv6-prefix
+++ b/etc/NetworkManager/dispatcher.d/08-ipv6-prefix
@@ -2,7 +2,7 @@
 # -*- mode: sh; sh-basic-offset: 2; indent-tabs-mode: nil; -*-
 # vim:set ft=sh et sw=2 ts=2:
 #
-# 08-ipv6-prefix v1.99.6 - NetworkManager dispatch for ipv6 prefix delegation
+# 08-ipv6-prefix v1.99.7 - NetworkManager dispatch for ipv6 prefix delegation
 # Author: Scott Shambarger <devel@shambarger.net>
 #
 # Copyright (C) 2014-2021 Scott Shambarger
@@ -177,7 +177,7 @@ NMDH6_DHCLIENT_ARGS=("-N")
 
 ########## SCRIPT START
 
-NMG_REQUIRED="1.5.8"
+NMG_REQUIRED="1.6.1"
 NMDDNS_REQUIRED="1.5.0"
 
 # load ddns- or general-functions
@@ -256,7 +256,7 @@ ipv6_life_calc() { # return 0 if <retval> set, 1 if offset unavailable
   # <retval> <life> <start>
   (( $2 >= 4294967295 )) && { printf -v "$1" "%s" "forever"; return 0; }
   [[ ${CUR_TIME} ]] || {
-    nmg::saferun CUR_TIME "" "${NMDATE}" "+%s" || CUR_TIME=0; }
+    nmg::saferun CUR_TIME "nolog" "${NMDATE}" "+%s" || CUR_TIME=0; }
   [[ ${CUR_TIME} == 0 ]] && return 1
   # sanity check time
   (( CUR_TIME < $3 )) && return 1
@@ -476,7 +476,7 @@ ipv6_lan_calc_address() { # returns 0 if <retvar> set
 
 ipv6_lan_start_cb() { # returns 0
   # <state-file> <iaid>-<wan>
-  local file=$1 state wan addr6
+  local sfile=$1 state wan addr6
 
   # should only remove "<iaid>-" since <iaid> cannot include "-"
   wan=${2#*-}
@@ -489,12 +489,12 @@ ipv6_lan_start_cb() { # returns 0
 
   # this LAN still configured for this WAN?
   [[ ${WAN_LAN_INTFS-} =~ (^| )"${interface}"($| ) ]] || {
-    nmg_remove "${file}"
+    nmg_remove "${sfile}"
     return 0
   }
 
   # read address from state
-  nmg::read state "info" "${file}" || return 0
+  nmg::read state "info" "${sfile}" || return 0
 
   if nmg::prop_get_value addr6 "${state}" "inet6" &&
       nmg::is_ip6_prefix "${addr6}"; then
@@ -502,13 +502,40 @@ ipv6_lan_start_cb() { # returns 0
     # try to calc address
     ipv6_lan_calc_address addr6 "${interface}" "${addr6}" "${LAN_NODE}" && {
       nmg::prop_set_value state "${state}" "inet6" "${addr6}"
-      nmg_write "${file}" "${state}" || :
+      nmg_write "${sfile}" "${state}" || :
     }
   fi
 
   ipv6_lan_add_addr "${interface}" "${state}"
 
   return 0
+}
+
+# check DAD, and remove address if failed
+ipv6_lan_check_dad() {
+  # <lan> <state-file>
+  local lan=$1 sfile=$2 state addr6
+
+  # did we even add the address?
+  if [[ -e "${sfile}" ]] && nmg::read state "nolog" "${sfile}" &&
+       nmg::prop_get_value addr6 "${state}" "inet6" &&
+       ! nmg::is_ip6_prefix "${addr6}"; then
+    # check DAD
+    nmg::wait_dad6 "${lan}" "${addr6}" || {
+      # only handle DAD failure (not timeout)
+      (( $? == 1 )) && {
+        nmg_err "Address ${addr6} has conflict on ${lan}"
+        ipv6_lan_node_remove "${sfile}" "${lan}"
+      }
+    }
+  fi
+
+  return 0
+}
+
+ipv6_lan_start_dad_cb() { # returns 0
+  # <state-file> <iaid>-<wan>
+  ipv6_lan_check_dad "${interface}" "$1"
 }
 
 ipv6_lan_start() {
@@ -522,6 +549,9 @@ ipv6_lan_start() {
 
   # set address from each WAN
   ipv6_lan_foreach_wan ipv6_lan_start_cb
+
+  # set address from each WAN
+  ipv6_lan_foreach_wan ipv6_lan_start_dad_cb
 
   ipv6_lan_handle_ddns "${LAN_STATE_PAT}"
 
@@ -786,6 +816,12 @@ ipv6_lan_node_assign() { # returns 0
   return 0
 }
 
+ipv6_lan_node_check_dad() {
+  # <lan>
+  ipv6_lan_check_dad \
+    "$1" "${LAN_STATE_PAT/@LAN@-from-@ID@-@WAN@/${1}-from-${Iaid}-${interface}}"
+}
+
 ipv6_prefix_load_assigned() {
   # <file> <lan>
   local file=$1 lan=$2 i state addr6 site6
@@ -894,6 +930,11 @@ ipv6_prefix_setup_nodes() {
     ipv6_lan_node_assign ${args}
   done
 
+  # check lan nodes for DAD failures
+  for args in ${Lans[*]+"${Lans[@]}"}; do
+    ipv6_lan_node_check_dad "${args%% *}"
+  done
+
   return 0
 }
 
@@ -952,9 +993,9 @@ ipv6_prefix_bind() {
 
   local na="${new_ip6_prefix}" oa="${old_ip6_prefix-}"
   if [[ ${oa} && ${na} != "${oa}" ]]; then
-    nmg_debug "prefix-bind - ${na} (old: ${oa})"
+    nmg_info "Prefix on ${interface}: ${na} (old: ${oa})"
   else
-    nmg_debug "prefix-bind - ${na}"
+    nmg_info "Prefix on ${interface}: ${na}"
   fi
 
   if [[ ${new_max_life-} == 0 ]]; then
@@ -980,7 +1021,7 @@ ipv6_prefix_bind() {
 
 ipv6_prefix_release() {
 
-  nmg_debug "prefix-release - ${old_ip6_prefix}"
+  nmg_info "Prefix removed from ${interface} - ${old_ip6_prefix}"
 
   ipv6_prefix_flush_iaid "${old_iaid}"
 
@@ -991,7 +1032,7 @@ ipv6_prefix_depref() {
 
   local id
 
-  nmg_debug "prefix-depref - ${cur_ip6_prefix}"
+  nmg_info "Prefix devalued on ${interface}: ${cur_ip6_prefix}"
 
   ipv6_verify_iaid id "${cur_iaid-}" && {
     # only process currently assigned lans...
@@ -1049,6 +1090,7 @@ ipv6_nm_reapply() { # returns 0 if applied ok, !0 if DAD failure
 
   [[ ${mod} ]] && {
     nmg_cmd "${NMCLI}" device reapply "${interface}" || return 0
+    # since NM will change accept_ra, we need to update it
     ipv6_update_ra
   }
 
@@ -1331,9 +1373,9 @@ ipv6_addr_bind() {
   local na="${new_ip6_address}/${new_ip6_prefixlen}"
   local oa="${old_ip6_address-}/${old_ip6_prefixlen-}"
   if [[ ${oa} != / && ${na} != "${oa}" ]]; then
-    nmg_debug "addr-bind - ${na} (old: ${oa})"
+    nmg_info "Address on ${interface}: ${na} (old: ${oa})"
   else
-    nmg_debug "addr-bind - ${na}"
+    nmg_info "Address on ${interface}: ${na}"
   fi
 
   ipv6_check_nm_or_fallback || return 0
@@ -1348,7 +1390,7 @@ ipv6_addr_bind() {
 
 ipv6_addr_release() {
 
-  nmg_debug "addr-release - ${old_ip6_address}/${old_ip6_prefixlen}"
+  nmg_info "Address removed from ${interface}: ${old_ip6_address}/${old_ip6_prefixlen}"
 
   ipv6_check_nm_or_fallback || return 0
 
@@ -1359,7 +1401,7 @@ ipv6_addr_release() {
 
 ipv6_addr_depref() {
 
-  nmg_debug "addr-depref - ${cur_ip6_address}/${cur_ip6_prefixlen}"
+  nmg_info "Address devalued on ${interface}: ${cur_ip6_address}/${cur_ip6_prefixlen}"
 
   ipv6_check_nm_or_fallback || return 0
 
diff --git a/test/ipv6-prefix-dhclient-test b/test/ipv6-prefix-dhclient-test
--- a/test/ipv6-prefix-dhclient-test
+++ b/test/ipv6-prefix-dhclient-test
@@ -400,6 +400,7 @@ xtest::group3::lan() {
   xwrap2 "<br0 brx, 88:99>" ipv6_dhc_bind
   xtest L2 t "returns true"
   xread_value out <<-EOF
+	Prefix on wan0: 2001:db8:100::/56
 	Adding 2001:db8:100:0:32fb:93c5:6555:845a/63 to br0
 	${NMG_IP} => ip '-6' 'addr' 'add'\
  '2001:db8:100:0:32fb:93c5:6555:845a/63' 'dev' 'br0' 'valid_lft' '180'\
@@ -430,6 +431,7 @@ xtest::group3::lan() {
   xwrap2 "<brx br0, 11:22>" ipv6_prefix_bind
   xtest L3 t "returns true"
   xread_value out <<-EOF
+	Prefix on wan0: 2001:db8:200::/56
 	Adding 2001:db8:200:0:32fb:93c5:6555:845a/63 to br0
 	${NMG_IP} => ip '-6' 'addr' 'add'\
  '2001:db8:200:0:32fb:93c5:6555:845a/63' 'dev' 'br0' 'valid_lft' '180'\
@@ -462,6 +464,7 @@ xtest::group3::lan() {
   xwrap2 "<brx br1, 11:22>" ipv6_prefix_bind
   xtest L4 t "returns true"
   xread_value out <<-EOF
+	Prefix on wan0: 2001:db8:200::/56
 	Adding 2001:db8:200:0:32fb:93c5:555:1/64 to br1
 	${NMG_IP} => ip '-6' 'addr' 'add'\
  '2001:db8:200:0:32fb:93c5:555:1/64' 'dev' 'br1'
@@ -497,6 +500,7 @@ xtest::group3::lan() {
   xwrap2 "<br1>" ipv6_prefix_bind
   xtest L5 t "returns true"
   xread_value out <<-EOF
+	Prefix on wan0: 2001:db8:200::/56
 	Replacing 2001:db8:200:2:32fb:93c5:555:1/64 on br1
 	${NMG_IP} => ip '-6' 'addr' 'replace'\
  '2001:db8:200:2:32fb:93c5:555:1/64' 'dev' 'br1'
@@ -539,6 +543,7 @@ xtest::group3::lan() {
   xwrap2 "<br1-with-old>" ipv6_prefix_bind
   xtest L6 t "returns true"
   xread_value out <<-EOF
+	Prefix on wan0: 2001:db8:200::/56 (old: 2001:db8:100::/56)
 	Removing 2001:db8:100:2:32fb:93c5:555:1/64 from br1
 	${NMG_IP} => ip '-6' 'addr' 'del'\
  '2001:db8:100:2:32fb:93c5:555:1/64' 'dev' 'br1'
@@ -585,6 +590,7 @@ xtest::group3::lan() {
   xwrap2 "<br1>" ipv6_prefix_bind
   xtest L7 t "returns true"
   xread_value out <<-EOF
+	Prefix on wan0: 2001:db8:100::/56
 	Replacing 2001:db8:100:2:32fb:93c5:555:1/64 on br1
 	${NMG_IP} => ip '-6' 'addr' 'replace'\
  '2001:db8:100:2:32fb:93c5:555:1/64' 'dev' 'br1'
@@ -649,6 +655,7 @@ xtest::group3::lan() {
   xwrap2 "<88:99>" ipv6_dhc_depref
   xtest L11 t "returns true"
   xread_value out <<-EOF
+	Prefix devalued on wan0: 2001:db8:100::/56
 	Adding 2001:db8:100:0:32fb:93c5:6555:845a/63 to br0
 	${NMG_IP} => ip '-6' 'addr' 'replace'\
  '2001:db8:100:0:32fb:93c5:6555:845a/63' 'dev' 'br0' 'valid_lft' '120'\
@@ -702,6 +709,7 @@ xtest::group3::lan() {
   xwrap2 "<br1, 88:99>" ipv6_prefix_depref
   xtest L12 t "returns true"
   xread_value out <<-EOF
+	Prefix devalued on wan0: 2001:db8:100::/56
 	Changing 2001:db8:100:2:32fb:93c5:555:1/64 on br1
 	${NMG_IP} => ip '-6' 'addr' 'change'\
  '2001:db8:100:2:32fb:93c5:555:1/64' 'dev' 'br1' 'valid_lft' '120'\
@@ -736,6 +744,7 @@ xtest::group3::lan() {
   xwrap2 "<88:99>" ipv6_dhc_release
   xtest L21 t "returns true"
   xread_value out <<-EOF
+	Prefix removed from wan0 - 2001:db8:100::/56
 	Removing 2001:db8:100:2:32fb:93c5:555:1/64 from br1
 	${NMG_IP} => ip '-6' 'addr' 'del'\
  '2001:db8:100:2:32fb:93c5:555:1/64' 'dev' 'br1'
@@ -787,6 +796,48 @@ xtest::group3::lan() {
   xtest::onexit::lan
 }
 
+xtest::onexit::lan_dad() {
+  [[ ${LAN_STATE_PAT-} ]] || return 0
+  local LAN_STATE_PAT="${LAN_STATE_PAT%-dhc}-dhc"
+  xrm "${LAN_STATE_PAT/@LAN@-from-@ID@-@WAN@/eth3-from-aabb-wan0=aabb}"
+}
+
+xtest::group3::lan_dad() {
+
+  local state1 out
+
+  local LAN_STATE_PAT="${LAN_STATE_PAT}-dhc"
+  state1=${LAN_STATE_PAT/@LAN@-from-@ID@-@WAN@/eth3-from-aabb-wan0=aabb}
+  xrm "$state1"
+
+  shtest::title "LAN Prefix DAD Failure Tests (lan_dad group)"
+
+  # Call ipv6_dhc_bind with prefix assignment that fails DAD on LAN
+
+  # check DAD failed
+  WAN_LAN_INTFS="eth3"
+
+  local new_ip6_prefix="2001:db8:5::/56" new_iaid="aa:bb"
+
+  xwrap2 F1"<eth3, aa:bb>" ipv6_dhc_bind
+  xtest F1 t "returns true"
+  xread_value out <<-EOF
+	Prefix on wan0: 2001:db8:5::/56
+	Replacing 2001:db8:5:0::1/64 on eth3
+	${NMG_IP} => ip '-6' 'addr' 'replace' '2001:db8:5:0::1/64' 'dev' 'eth3'
+	ERR: Address 2001:db8:5:0::1/64 has conflict on eth3
+	Removing 2001:db8:5:0::1/64 from eth3
+	${NMG_IP} => ip '-6' 'addr' 'del' '2001:db8:5:0::1/64' 'dev' 'eth3'
+	${NMG_RADVD_TRIGGER} => radvd triggered
+	EOF
+  ftest F1f "$out" "adds/removes ip"
+  [[ -e $state1 ]]
+  xtest F1s f "should not create state file"
+
+  ipv6_lan_reset_config
+  xtest::onexit::lan_dad
+}
+
 xtest::onexit::wan_start() {
   [[ ${WAN_STATE_PAT-} ]] || return 0
   local file="${WAN_STATE_PAT%-dhc}-dhc"
@@ -824,7 +875,7 @@ xtest::group3::wan_start() {
 
   xwrap2 "<exiting addr>" ipv6_dhc_bind
   xtest W11 t "returns true"
-  ftest W11f "" "does nothing"
+  ftest W11f "Address on wan0: 2001:db8:800::2/64" "does nothing"
   shtest::check_file W11s "$state1" "inet6:2001:db8:800::2/64" \
                      "creates state file"
 
@@ -834,6 +885,7 @@ xtest::group3::wan_start() {
   xwrap2 "<new lifetimes>" ipv6_addr_bind
   xtest W12 t "returns true"
   xread_value out <<-EOF
+	Address on wan0: 2001:db8:800::2/64
 	Changing 2001:db8:800::2/64 on wan0
 	${NMG_IP} => ip '-6' 'addr' 'change' '2001:db8:800::2/64'\
  'dev' 'wan0' 'valid_lft' '3600' 'preferred_lft' '1800'
@@ -854,6 +906,7 @@ xtest::group3::wan_start() {
   xwrap2 "<moving addr>" ipv6_addr_bind
   xtest W13 t "returns true"
   xread_value out <<-EOF
+	Address on wan0: 2001:db8:aaa::2/64 (old: 2001:db8:800::2/64)
 	${NMCLI} => nmcli 'conn' 'modify' '--temporary' '${isp_uuid}'\
  'ipv6.method' 'manual' 'ipv6.addresses' '2001:db8:aaa::2/64'\
  'ipv6.dns' '' 'ipv6.dns-search' ''
@@ -881,6 +934,7 @@ xtest::group3::wan_start() {
   xwrap2 "<static dns>" ipv6_addr_bind
   xtest W14 t "returns true"
   xread_value out <<-EOF
+	Address on wan0: 2001:db8:800::2/64
 	${NMCLI} => nmcli 'conn' 'modify' '--temporary' '${isp_uuid}'\
  'ipv6.method' 'manual' 'ipv6.addresses'\
  '2001:db8:55::1/64,2001:db8:100::1/64,2001:db8:800::2/64'\
@@ -899,6 +953,7 @@ xtest::group3::wan_start() {
   xwrap2 "<static/dhcp dns>" ipv6_addr_bind
   xtest W15 t "returns true"
   xread_value out <<-EOF
+	Address on wan0: 2001:db8:800::2/64
 	${NMCLI} => nmcli 'conn' 'modify' '--temporary' '${isp_uuid}'\
  'ipv6.method' 'manual' 'ipv6.addresses'\
  '2001:db8:55::1/64,2001:db8:100::1/64,2001:db8:800::2/64' 'ipv6.dns'\
@@ -923,6 +978,7 @@ xtest::group3::wan_start() {
   xwrap2 "<no-auto-dns>" ipv6_addr_bind
   xtest W16 t "returns true"
   xread_value out <<-EOF
+	Address on wan0: 2001:db8:800::2/64
 	${NMCLI} => nmcli 'conn' 'modify' '--temporary' '${isp_uuid}'\
  'ipv6.method' 'manual' 'ipv6.addresses'\
  '2001:db8:55::1/64,2001:db8:800::2/64' 'ipv6.dns' '2001:db8:aaaa::1'\
@@ -944,6 +1000,7 @@ xtest::group3::wan_start() {
   xwrap2 "<dhcp only dns>" ipv6_addr_bind
   xtest W17 t "returns true"
   xread_value out <<-EOF
+	Address on wan0: 2001:db8:800::2/64
 	${NMCLI} => nmcli 'conn' 'modify' '--temporary' '${isp_uuid}'\
  'ipv6.method' 'manual' 'ipv6.addresses' '2001:db8:800::2/64'\
  'ipv6.dns' '2001:db8:111::1,2001:db8:222::1'\
@@ -967,6 +1024,7 @@ xtest::group3::wan_start() {
   xwrap2 "<new ip/lifetimes>" ipv6_addr_bind
   xtest W18 t "returns true"
   xread_value out <<-EOF
+	Address on wan0: 2001:db8:800::2/64
 	${NMCLI} => nmcli 'conn' 'modify' '--temporary' '${isp_uuid}'\
  'ipv6.method' 'manual' 'ipv6.addresses' '2001:db8:800::2/64'\
  'ipv6.dns' '' 'ipv6.dns-search' ''
@@ -990,6 +1048,7 @@ xtest::group3::wan_start() {
   xwrap2 "<2nd ip>" ipv6_addr_bind
   xtest W19 t "returns true"
   xread_value out <<-EOF
+	Address on wan0: 2001:db8:800::2/64
 	${NMCLI} => nmcli 'conn' 'modify' '--temporary' '${isp_uuid}'\
  'ipv6.method' 'manual' 'ipv6.addresses'\
  '2001:db8:800::2/64,2001:db8:800::2/64' 'ipv6.dns' '' 'ipv6.dns-search' ''
@@ -1035,6 +1094,7 @@ xtest::group3::wan_depref() {
   xwrap2 "<depref new>" ipv6_dhc_depref
   xtest E1 t "returns true"
   xread_value out <<-EOF
+	Address devalued on wan0: 2001:db8:800::2/64
 	${NMCLI} => nmcli 'conn' 'modify' '--temporary' '${isp_uuid}'\
  'ipv6.method' 'manual' 'ipv6.addresses' '2001:db8:800::2/64'\
  'ipv6.dns' '' 'ipv6.dns-search' ''
@@ -1058,6 +1118,7 @@ xtest::group3::wan_depref() {
   xwrap2 "<depref exist>" ipv6_addr_depref
   xtest E2 t "returns true"
   xread_value out <<-EOF
+	Address devalued on wan0: 2001:db8:800::2/64
 	Changing 2001:db8:800::2/64 on wan0
 	${NMG_IP} => ip '-6' 'addr' 'change' '2001:db8:800::2/64'\
  'dev' 'wan0' 'valid_lft' '1700' 'preferred_lft' '0'
@@ -1110,6 +1171,7 @@ xtest::group3::wan_ddns() {
   xwrap2 "<exiting addr>" ipv6_addr_bind
   xtest D1 t "returns true"
   xread_value out <<-EOF
+	Address on eth0: 2001:db8:871a:28c1::1/64
 	Setting eth0.example.test AAAA to 2001:db8:871a:28c1::1
 	${NMDDNS_NSUPDATE} => nsupdate '-t' '2'
 	server 127.0.0.1
@@ -1136,6 +1198,7 @@ xtest::group3::wan_ddns() {
   xwrap2 "<2nd addr>" ipv6_addr_bind
   xtest D2 t "returns true"
   xread_value out <<-EOF
+	Address on eth0: 2001:db8:4860:4860::8888/64
 	Setting eth0.example.test AAAA to\
  2001:db8:871a:28c1::1,2001:db8:4860:4860::8888
 	${NMDDNS_NSUPDATE} => nsupdate '-t' '2'
@@ -1160,6 +1223,7 @@ xtest::group3::wan_ddns() {
   xwrap2 "<1/2 removed>" ipv6_dhc_release
   xtest D11 t "returns true"
   xread_value out <<-EOF
+	Address removed from eth0: 2001:db8:871a:28c1::1/64
 	${NMCLI} => nmcli 'conn' 'modify' '--temporary' '${office_uuid}'\
  'ipv6.method' 'manual' 'ipv6.addresses' '2001:db8:4860:4860::8888/64'\
  'ipv6.dns' '' 'ipv6.dns-search' ''
@@ -1186,6 +1250,7 @@ xtest::group3::wan_ddns() {
   xwrap2 "<2nd removed>" ipv6_addr_release
   xtest D12 t "returns true"
   xread_value out <<-EOF
+	Address removed from eth0: 2001:db8:4860:4860::8888/64
 	${NMCLI} => nmcli 'conn' 'modify' '--temporary' '${office_uuid}'\
  'ipv6.method' 'link-local' 'ipv6.addresses' '' 'ipv6.dns' ''\
  'ipv6.dns-search' ''
