Updated copyright and indentation, added editor flags

diff --git a/etc/NetworkManager/dispatcher.d/09-ddns b/etc/NetworkManager/dispatcher.d/09-ddns
--- a/etc/NetworkManager/dispatcher.d/09-ddns
+++ b/etc/NetworkManager/dispatcher.d/09-ddns
@@ -1,9 +1,10 @@
 #!/bin/bash
+# vim:set ft=sh et sw=2 ts=2:
 #
 # 09-nmddns v1.0.1 - NetworkManager dispatch for ipv4 Dynamic DNS updates
 # Author: Scott Shambarger <devel@shambarger.net>
 #
-# Copyright 2014 Scott Shambarger.  All rights reserved.
+# Copyright (C) 2014, 2016 Scott Shambarger
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -69,8 +70,8 @@ RUNDIR="${RUNDIR:-/run/nmutils}"
 # load ddns-functions
 NMDDNS="${NMDDNS:-$NMUTILS/ddns-functions}"
 [ -f "$NMDDNS" -a -r "$NMDDNS" ] && . "$NMDDNS" || {
-  echo 1>&2 "Unable to load $NMDDNS" && exit 2
-}
+    echo 1>&2 "Unable to load $NMDDNS" && exit 2
+  }
 
 ########## Config/state locations
 
@@ -135,3 +136,9 @@ case "$action" in
     nmddns_spawn_update "$DDNS_CONFIG" "AAAA" "$(ddns_addr6)" "$DDNS_STATE_PAT"
     ;;
 esac
+# Local Variables:
+# mode: sh
+# sh-basic-offset: 2
+# sh-indentation: 2
+# indent-tabs-mode: nil
+# End:
diff --git a/etc/NetworkManager/dispatcher.d/90-transmission b/etc/NetworkManager/dispatcher.d/90-transmission
--- a/etc/NetworkManager/dispatcher.d/90-transmission
+++ b/etc/NetworkManager/dispatcher.d/90-transmission
@@ -1,4 +1,5 @@
 #!/bin/bash
+# vim:set ft=sh et sw=2 ts=2:
 #
 # 90-transmission v1.0.0 - Transmission dispatcher script
 # Author: Scott Shambarger <devel@shambarger.net>
@@ -9,7 +10,7 @@
 # configuration and then start transmission on interface up,
 # and stop transmission on interface down.
 #
-# Copyright 2015 Scott Shambarger.  All rights reserved.
+# Copyright (C) 2015 Scott Shambarger
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -92,8 +93,8 @@ TR_UNIT="transmission-daemon"
 # load general-functions
 NMG="${NMG:-$NMUTILS/general-functions}"
 [ -f "$NMG" -a -r "$NMG" ] && . "$NMG" || {
-  echo 1>&2 "Unable to load $NMG" && exit 2
-}
+    echo 1>&2 "Unable to load $NMG" && exit 2
+  }
 
 # see if we're configured for this interface
 nmg_read_config "$TR_CONFIG" || exit 0
@@ -149,3 +150,9 @@ case "$action" in
     tr_stop
     ;;
 esac
+# Local Variables:
+# mode: sh
+# sh-basic-offset: 2
+# sh-indentation: 2
+# indent-tabs-mode: nil
+# End:
diff --git a/etc/nmutils/interface-dispatcher b/etc/nmutils/interface-dispatcher
--- a/etc/nmutils/interface-dispatcher
+++ b/etc/nmutils/interface-dispatcher
@@ -1,7 +1,23 @@
 #!/bin/sh
+# vim:set ft=sh et sw=2 ts=2:
 #
 # /etc/nmutils/interface-dispatcher v0.9
 # Author: Scott Shambarger <devel@shambarger.net>
+#
+# Copyright (C) 2015 Scott Shambarger
+#
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 3 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 # Copy this file to /etc/NetworkManager/dispatcher.d/<##>-<service>
 # (or wherever your distro has these files) where <##> is a 2-digit
@@ -42,8 +58,8 @@ NMCONF="${NMCONF:-$NMUTILS/conf}"
 # load general-functions
 NMG="${NMG:-$NMUTILS/general-functions}"
 [ -f "$NMG" -a -r "$NMG" ] && . "$NMG" || {
-  echo 1>&2 "Unable to load $NMG" && exit 2
-}
+    echo 1>&2 "Unable to load $NMG" && exit 2
+  }
 
 # check dispatcher name format for ##-service
 echo $0 | /bin/grep -q '^.*[0-9][0-9]-'
@@ -83,3 +99,9 @@ case "$action" in
 esac
 
 exit 0
+# Local Variables:
+# mode: sh
+# sh-basic-offset: 2
+# sh-indentation: 2
+# indent-tabs-mode: nil
+# End:
diff --git a/sbin/nmddns-helper b/sbin/nmddns-helper
--- a/sbin/nmddns-helper
+++ b/sbin/nmddns-helper
@@ -1,9 +1,10 @@
 #!/bin/bash
+# vim:set ft=sh et sw=2 ts=2:
 #
-# nmddns-helper v1.0.0 - NMUtils Dynamic DNS helper program
+# nmddns-helper v1.0.1 - NMUtils Dynamic DNS helper program
 # Author: Scott Shambarger <devel@shambarger.net>
 #
-# Copyright 2014 Scott Shambarger.  All rights reserved.
+# Copyright (C) 2014, 2018 Scott Shambarger
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -33,10 +34,10 @@
 #   $NMUTILS/ddns-functions - Dynamic DNS functions
 #   $NMUTILS/general-functions - shared functions, used by ddns-functions
 #
-# Supported, but optional:
+# Optional, but suggested:
 #
 #   /etc/NetworkManager/dispatcher.d/09-ddns - NM trigger script
-#   /etc/systemd/system/nmddns-onboot@<interface>.service (systemd)
+#   /etc/systemd/system/ddns-onboot@<interface>.service (systemd)
 #   rc.local (add "nmddns-helper [<interface>]")
 #
 
@@ -58,8 +59,8 @@ RUNDIR="${RUNDIR:-/run/nmutils}"
 # load ddns-functions
 NMDDNS="${NMDDNS:-$NMUTILS/ddns-functions}"
 [ -f "$NMDDNS" -a -r "$NMDDNS" ] && . "$NMDDNS" || {
-  echo 1>&2 "Unable to load $NMDDNS" && exit 2
-}
+    echo 1>&2 "Unable to load $NMDDNS" && exit 2
+  }
 
 ########## Config locations
 
@@ -175,3 +176,9 @@ if [ -z "${2:-}" ]; then
 else
   ddns_helper_action "$@"
 fi
+# Local Variables:
+# mode: sh
+# sh-basic-offset: 2
+# sh-indentation: 2
+# indent-tabs-mode: nil
+# End:
